### ISSUE TITLE
Show 🚫 when first boot

### ISSUE THREAD

**Issue by zybzzc** [zearp/Nucintosh#104]
I upgrade from 12 to 13, replace all EFI with this repo(include config.plist, but replaced Serial Numbers with old), repalce bluetooth kexts according to the tutorial(BCM94360CS2).
Everything word well but will show forbidden sign when first boot, I have to reboot or wait it go back to boot list and get in.
I tried Reset NVRAM but not working.

![截屏2022-12-03 14 06 35](https://user-images.githubusercontent.com/12845870/205427207-f8972f2e-6ef1-4351-aa65-043ba9f16796.png)

**Comment by zearp** [comment]
What are steps to reproduce this? The issues aren’t a helpdesk but a place to report issues with the EFI.

**Comment by vardumper** [comment]
Unfortunately, I am having the same problem. I as well can't tell you how to reproduce this, but have some observations:
* before macOS 13, I basically had a very similar issue, where upon manual or auto boot selection (usually macOS HD) the screen went black for about 5-7secs. After that, the boot menu re-appeared, I would manually select the startup disk again. On enter it would either go back to black for another 5-7 secs or actually boot. As soon as the verbose output shows I knew, that it's booting. Sometimes I had to repeat this step for up to 5 times.

Now, with macOS 13, for me it's exactly like in 12 but now instead of a black screen is also see the 🚫. So for me it seems that something that didn't work before, now works – which is why I see the 🚫.

But yes, I would have to guess what the cause is, but I can confirm @zybzzc observation. Ow, btw. I am using the iMac instead Mac Mini in SMBIOS, too. What do you use @zybzzc? I did see your comment @zearp where you said, that it's not that simple as just changing the name – but I don't think this is related, a s I saw that behaviour before as well. (with Mac Mini).

**Comment by zearp** [comment]
What might happen during install is that OpenCore doesn't boot into the right volume and it gets confused? Usually the prohibited sign means it can't find the disk to boot macOS from. Which can be caused by a number of things. Maybe it's the NVMe kext which should be disabled when not using an NVMe drive. 

The problem with things I can't reproduce is the I can only make guesses. If there are some steps that always results in the issue I can try it myself and then it's a lot easier to fix. I'm not trying to be mean but realistic and it doesn't help anyone if I make 10 guesses that need you guys to do try or test something that might not even fix it.

As it might be related to macOS and certain SSD's I would try another brand of disk if you have one laying around. I do a clean install on my test NUC quite often but haven't run into anything close to this. The only issue I sometimes have is that OpenCore boots the wrong volume when installing. But thats easily solved by baby sitting and watching the menu when it reboots during installation or updates.

**Comment by vardumper** [comment]
Great tip. I'll try that when I do a complete fresh install (which I hopefully don't need). To clarify I do use a NVMe, there's no SATA connected. Maybe some bios setting, boot priority or something could cause this too

**Comment by zearp** [comment]
I'm not near my NUC at the moment but if you can change the boot order you can test it by putting the NVMe on top. Also the kext is good for most NVMe's as it fixes power management and other stuff but its not a fits all solution, you can try booting without it and maybe that helps.

Also check if your drive has the latest firmware. A while back I think it was Crucial had some bug where performance was very poor in macOS and the drives needed a firmware update to get the promised performance.

Then there's also the fact some hardware including drivers just don't work with macOS properly or work at all. Not all hardware is designed for, or even tested on macOS by manufactures. We either have to be "lucky" Apple supports it or the manufacturer has a good driver for it. Many so called Mac compatible wireless usb sticks are complete crap and use very bad software and drivers. Others do it much better and get their drivers shipped with macOS by Apple themselves (like CalDigit).

It can't harm to make sure things are Mac compatible and they provide decent drivers and software. I forgot the latter with a new screen I got and while it works with macOS I can't change the brightness from macOS or access the screen settings using an app like I can in Windows.
