### ISSUE TITLE
Unknown card is displayed

### ISSUE THREAD

**Issue by Bourns** [zearp/Nucintosh#115]
The SD card reader is displayed as "unknown card" and SD cards are not recognized. 
How is it be possible to recognize the card reader as native. Does anyone know the solution?

The Solution in next Link is not working.
https://www.reddit.com/r/hackintosh/comments/o6ui3b/i_got_my_realtek_sd_card_reader_working_in_macos/ 

![234](https://user-images.githubusercontent.com/47642062/225999283-b4ac92dc-cf17-4aea-af16-7190016a4c78.png)
![123](https://user-images.githubusercontent.com/47642062/225999287-c3216075-7c02-40a8-a96e-d53ee4b638e5.png)

**Comment by zearp** [comment]
I don't understand the issue. Drivers for the Realtek card reader have been added a while ago and works as good/bad as possible within the limits of porting a driver from another OS. The card reader is detected as native (see image) this is done by RealtekCardReaderFriend kext.

![Screenshot 2023-03-17 at 22 18 49](https://user-images.githubusercontent.com/63272687/226055116-9e20a882-9943-4dad-8213-93d50a8d882d.png)

The icon also has been present since the start. It is a macOS feature that shows ups when it detects certain hardware.

To hide it use an app like HiddenBar or Bulldozer as disabling it on modern macOS versions would mean you have to reduce the security of the system by disabling SIP and file system protection which also makes it so you will no longer receive macOS updates.

What is the issue exactly? Does the card reader not work? Does the icon bother you? I'm sorry but I don't get it.

**Comment by zearp** [comment]
```
A Lilu plugin that makes System Information recognize your Realtek card reader as a native one.
```
https://github.com/0xFireWolf/RealtekCardReaderFriend

```
An unofficial macOS kernel extension for Realtek PCIe/USB-based SD card readers.
It uses the Linux driver as a reference implementation but is written from scratch and carefully designed for macOS to deliver the best performance.
```
https://github.com/0xFireWolf/RealtekCardReader

**Comment by zearp** [comment]
As for card compatibility not all cards will work. Most cards I tested worked but not all. Thats just part of running hardware with drivers from another OS. We should be happy we can read/write to most cards. If you require better compatibility you can buy a macOS supported card reader that uses usb or a Thunderbolt dock. Just make sure macOS supports it. As for the internal reader this is is good as it gets unless someone improves the driver I linked above.

![Screenshot 2023-03-17 at 22 33 38](https://user-images.githubusercontent.com/63272687/226057643-c09f5f4c-dddd-4626-886b-a702110c0191.png)

Just tried a Samsung 128GB card and it works fine. I can't fix the driver to support cards it doesn't support. According to the driver page these are supported:

- Supports SDSC/HC/XC cards
- Supports UHS-I SDR12/25/50/104 and DDR50 modes

You can open an issue there if you can help them debug and improve the driver but it seems developed has stopped.
