### ISSUE TITLE
windows to mac into a purple screen

### ISSUE THREAD

**Issue by LimonChoms** [zearp/Nucintosh#119]
After restarting from windows to mac, the monitor will turn into a purple screen, has anyone encountered this? 
Rebooting from mac to windows does not have this problem, or completely shutting down from windows and then booting into the mac is no problem, I use hdmi to hdmi cable
mac：ventura 13.2.1
win：windows11 22h2
![802D88FF-B640-4F5A-B5D7-85D9792E1DFC_1_102_o](https://user-images.githubusercontent.com/46754160/227745736-26912fcc-8bb1-4568-88bd-f3777b2ea7e5.jpeg)

**Comment by zearp** [comment]
It's a firmware issue most likely. Turning the pc off will fix it as it flashes the firmware. I noticed this too when booting back into macOS after using Linux. Maybe WhateverGreen isn't reloading the GuC firmware or something related to that. I don't know. To fix it just shutdown instead of rebooting. You can also try disabling loading the GuC firmware but that might not do anything as the firmware cousin the hue isn't replaced when booting macOS. I checked the WhatEverGreen docs and there doesn't seem to be a way to force reloading a firmware. To disable loading of that firmware remove ```igfxfw=2``` from the frame buffer settings.

**Comment by zearp** [comment]
It's a firmware issue most likely. Turning the pc off will fix it as it flushes the firmware. I noticed this too when booting back into macOS after using Linux. Maybe WhateverGreen isn't reloading the firmware or something related to that properly. I don't know.

You can also try disabling loading the GuC firmware but that might not do anything as the firmware cousin the hue isn't replaced when booting macOS. I checked the WhatEverGreen docs and there doesn't seem to be a way to force reloading a firmware. To disable loading of that firmware remove ```igfxfw=2``` from the frame buffer settings.

**Comment by zearp** [comment]
It's a firmware issue most likely. Turning the pc off will fix it as it flushes the firmware. I noticed this too when booting back into macOS after using Linux. Maybe WhateverGreen isn't reloading the firmware or something related to that properly. I don't know.

You can also try disabling loading the GuC firmware but that might not do anything as the firmware causing the hue isn't replaced when booting macOS. I checked the WhateverGreen docs and there doesn't seem to be a way to force reloading flushing the firmware.

To disable loading of that firmware remove ```igfxfw=2``` from the frame buffer setting. This will reduce performance when it comes to encoding and decoding videos.
