### ISSUE TITLE
How do I stop MicroSD port from loading up on boot?

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#123]
Hey, please help.

So I moved RealtekCardReader.kext and RealtekCardReaderFriend.kext from the kexts directory, ran a clean OC snapshot in ProperTree and this thing still shows up. What loads it?

I'm using a Cirrus7 fanless case that has the MicroSD card slot blocked and I don't use it.

See image:

![Screenshot](https://user-images.githubusercontent.com/38587586/232640949-638b77ff-4d5e-4706-9301-649281784f17.png)

**Comment by zearp** [comment]
Tried disabling it in the bios?

**Comment by zearp** [comment]
Even if you disable sd card in the bios, which you should if you don't use it the icon will not disappear. The only way to remove it is to break the seals on the filesystem which will in turn prevent Apple from gibing you updates. They changed that since I think Big Sur.

Before Big Sur you could simply delete the preference pane file for it and the icon won't show. To hide it now use HiddenBar or Bulldozer or something like that. You could also try an ACPI patch to hide it. Personally I need to hide more icons so I use Hiddenbar. This is mentioned in the readme too but I did remove the preference pane part as it breaks too much on modern macOS.

https://github.com/dwarvesf/hidden

If you don't care about file system integrity, security updates and breaking macOS a bit you can disable SIP, and also disable the file system protections all using the ```csrutil``` from a recovery boot. The file you want to delete is ```/System/Library/CoreServices/Menu\ Extras/ExpressCard.menu```. Good luck!

**Comment by zearp** [comment]
Even if you disable sd card in the bios, which you should if you don't use it the icon will not disappear. The only way to remove it is to break the seals on the filesystem which will in turn prevent Apple from giving you updates. They changed that since I think Big Sur. I tested it at the time and breaking the filesystem seals wil cause software update to not show any updates or fail to install them.

Before Big Sur you could simply delete the preference pane file for it and the icon won't show. To hide it now use HiddenBar or Bulldozer or something like that. You could also try an ACPI patch to hide it. Personally I need to hide more icons so I use Hiddenbar. This is mentioned in the readme too but I did remove the preference pane part as it breaks too much on modern macOS.

https://github.com/dwarvesf/hidden

If you don't care about file system integrity, security updates and breaking macOS a bit you can disable SIP, and also disable the file system protections all using the ```csrutil``` from a recovery boot. The file you want to delete is ```/System/Library/CoreServices/Menu\ Extras/ExpressCard.menu```.

Good luck!

**Comment by naryfa** [comment]
Very detailed answer, thank you so much. Tried renaming the ExpressCard.menu and got an error that it's a read-only file system. Don't want to unseal it. I'll pass and live with it. 

But hey... pretty soon we'll be able to only access the user folder and that's it 😂

**Comment by zearp** [comment]
Haha. It is not a bad system if you can control it as end user, such as adding files or removing them in some way and reseal the volume. Like on Linux. A stateless system where user and system files are separated for security and stability is not bad in principle.

Personally I wouldn’t mind breaking the seal if updates remain working properly but they either refuse to install if fail due to the seal being broken. Last time I checked it was not possible to seal the volume. I think only Apple can with their keys.

I’ll check it out again soon as I’m working on a little macOS lite side project that requires me to delete a lot of stuff and I’d like to keep as much security in place. Including auto updates.
