### ISSUE TITLE
Onboard Intel bluetooth stoped working after upgrade macOS from 13.3.1(a) to 13.4

### ISSUE THREAD

**Issue by 70599** [zearp/Nucintosh#128]
Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
    - Try to performing OTA upgrade. → "Failed to prepare the software update, please try again"
    - Disable BlueToolFixup and then reboot.
    - Try to performing OTA upgrade, again. → Successed.
        - Enabled BlueToolFixup before the first reboot.
    - Rebooted about twice during upgrade.
    - Bluetooth is not able to turn on.
- macOS version and optionally the build number
    - Upgraded from 13.3.1(a) to 13.4.
- Any changes you made to the config and/or EFI other than serials/etc
    - Disabled BlueToolFixup before OTA upgrade, and enabled it after upgrade.
- Any logs related to the issue if applicable
    - Not yet collected. (Do not know how to).

**Comment by zearp** [comment]
13.4 was released one day ago. I have not tried it but if it breaks something there is nothing I can do about it as I don’t maintain the underlaying kexts. I’ll see when I can update.

**Comment by zearp** [comment]
I can reproduce the issue and it is also reported by others already. We'll have to wait for an updated kext that fixes this. Mind you, Intel bluetooth is not natively supported. Funnily enough some $1 bt dongles from eBay work on macOS natively but there's no list of supported modules on apple's website or anything. It is really a gamble with those dongles. We'll have to wait for upstream to fix this in order to use Intel bluetooth on 13.4.

https://github.com/acidanthera/bugtracker/issues/1821

**Comment by zearp** [comment]
I've made a new issue to keep track of things relating to the update. More things might have changed and no longer work as it should. Very unlike Apple to introduce big changes to stuff like the bluetooth stack in a minor update. Let's hope the issues can be easily fixed upstream. Till then its best to stay on 13.3.x if you need Intel wireless/bluetooth.

https://github.com/zearp/Nucintosh/issues/129

**Comment by qcTimb3rlandqc** [comment]
;)
