### ISSUE TITLE
USB-C port doesn't seem to work

### ISSUE THREAD

**Issue by stf1o** [zearp/Nucintosh#13]
Hello, I followed your bios settings and just tried to plug my iPad on the NUC but it doesn't seem to show the device in either System information under usb devices or either in the finder sidebar.
I just connected the usb-c cable, nothing happens, it just charges the device. When I use the usb-a port it works normally. 
Am I missing something?
Thank you!

**Comment by zearp** [comment]
Connect your usb-c iPad and check in Hackintool on the usb tab, if you see nothing try selecting all devices, remove them and then press the refresh button in there. You can also use ioreg.

Maybe some parts of the usb-c stuff still need to be mapped though I did map the 2 internal Thunderbolt USB ports that were shown as can be seen [here](https://github.com/zearp/Nucintosh/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L53-L70). Bit it may be possible it has more ports that don't show up now cuz they're not in the map and weren't mapped cuz I simply don't have the devices to test it with.

You can try remaking the usb map; disable USBPorts.kext, add USBInjectAll.kext, reboot and map the ports in Hackintool. Maybe there's some new ones showing up that I couldn't map but I doubt it since usb-c is just usb-c. If my hub works on there then so should your iPad. But I'm curious as to what it shows in Hackintool or ioreg. I wonder if I could reproduce the issue if I convert a normal usb-a to usb-c with some plug, but I also don't have one of those laying around.

Sp for now I can't do anything else than guess cuz I don't have a usb-c iPad and all my other usb-c devices work fine. Let me know how it goes.

**Comment by zearp** [comment]
Connect your usb-c iPad and check in Hackintool on the usb tab, if you see nothing try selecting all devices, remove them and then press the refresh button in there. You can also use ioreg.

Maybe some parts of the usb-c stuff still need to be mapped though I did map the 2 internal Thunderbolt USB ports that were shown as can be seen [here](https://github.com/zearp/Nucintosh/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L53-L70). But it may be possible it has more ports that don't show up now cuz they're not in the map and weren't mapped cuz I simply don't have the devices to test it with.

You can try remaking the usb map; disable USBPorts.kext, add USBInjectAll.kext, reboot and map the ports in Hackintool. Maybe there's some new ones showing up that I couldn't map but I doubt it since usb-c is just usb-c. If my hub works on there then so should your iPad. But I'm curious as to what it shows in Hackintool or ioreg. I wonder if I could reproduce the issue if I convert a normal usb-a to usb-c with some plug, but I also don't have one of those laying around.

Sp for now I can't do anything else than guess cuz I don't have a usb-c iPad and all my other usb-c devices work fine. Let me know how it goes.

**Comment by zearp** [comment]
Connect your usb-c iPad and check in Hackintool on the usb tab, if you see nothing try selecting all devices, remove them and then press the refresh button in there. You can also use ioreg to check before and after you plug it in.

Maybe some parts of the usb-c stuff still need to be mapped, though I did map the 2 internal Thunderbolt usb ports that were shown as can be seen [here](https://github.com/zearp/Nucintosh/blob/master/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L53-L70). But it's possible it has more ports that don't show up now cuz they're not in the map and weren't mapped by me cuz I simply don't have the devices to map it with. I only have usb-c hubs and they work fine.

You can try remaking the usb map; disable USBPorts.kext, add USBInjectAll.kext, reboot and map the ports in Hackintool. Maybe there's some new ones showing up that I couldn't map but I doubt it since usb-c is just usb-c. If my hub works on there then so should your iPad. But I'm curious as to what it shows in Hackintool or ioreg. I also wonder if I could reproduce the issue if I convert a normal usb-a to usb-c with one of those 99 cent plugs, but I also don't have one of those laying around.

So for now I can't do anything else than guess cuz I don't have a usb-c iPad and all my other usb-c devices work fine. Let me know how it goes.

**Comment by zearp** [comment]
I found a few of these plugs can converts usb-a to usb-c and tested some devices with it, including my own iPad. Everything works as expected. IT would be nice if you can repeat these tests too. Like one test where you convert the usb-c end of the iPad cable to usb-a and one test where you convert the usb-a end of the iPad club to usb-c. Also are you 100% sure your usb-c cable can do data? Not all usb-c cables are created qual. Some can ***only*** do charging.

**Comment by zearp** [comment]
I found a one of these plugs that converts usb-a to usb-c and tested some devices with it, including my iPad. Everything works as expected. IT would be nice if you can repeat these tests too. Like one test where you convert the usb-c end of the iPad cable to usb-a and one test where you convert the usb-a end of the iPad club to usb-c. Also are you 100% sure your usb-c cable can do data? Not all usb-c cables are created qual. Some can ***only*** do charging.

**Comment by zearp** [comment]
I found a few of these plugs can converts usb-a to usb-c and tested some devices with it, including my own iPad. Everything works as expected. It would be nice if you can repeat these tests too. Like one test where you convert the usb-c end of the iPad cable to usb-a and one test where you convert the usb-a end of the iPad club to usb-c. Also are you 100% sure your usb-c cable can do data? Not all usb-c cables are created qual. Some can ***only*** do charging.

**Comment by zearp** [comment]
I found a few of these plugs can converts usb-a to usb-c and tested some devices with it, including my iPad. Everything works as expected. IT would be nice if you can repeat these tests too. Like one test where you convert the usb-c end of the iPad cable to usb-a, and one test where you convert the usb-a end of the iPad club to usb-c. Also are you 100% sure your usb-c cable can do data? Not all usb-c cables are created equal. Some can ***only*** do charging.

**Comment by stf1o** [comment]
Hi, first of all thank you for these answers. I've read the previous one earlier today and firstly decided to reply only this evening (after having run those tests). I confirm I will follow your instructions and I will get back here and report what I can find. I'm also gonna buy the usb-c converters like you said if the port doesn't seem to work this evening.
Thank you for your time

**Comment by zearp** [comment]
Awesome, make sure the converters support data. Some of the cheapest ones only do charging. Usb-c land is pretty confusing/annoying, specially if you also take into account some cables/adapters do data but only at 2.0 speeds, others only charge at certain voltages and nothing higher. And combinations of the those too. It can get pretty tedious.

**Comment by stf1o** [comment]
Hey, it seems it was just a cable issue after all. Pretty shocking to discover the stock iPad usb-c cable doesn't work meanwhile a cheap Anker one does.
I apologize for wasting your time and I also thank you for your help and support and again for all your work with Nucintosh

**Comment by zearp** [comment]
No problem, I'm glad you found the culprit. Maybe the NUC is more picky or the cable itself passed QC when it really shouldn't have. Either way it's solved now, now you can enjoy your NUC and use your iPad to extend your desktop with Sidecar!

**Comment by zearp** [comment]
No problem, I'm glad you found the culprit. Maybe the NUC is more picky or the cable itself passed QC when it really shouldn't have. Either way it's solved, now you can enjoy your NUC and use your iPad to extend your desktop with Sidecar!
