### ISSUE TITLE
A Quick Question about AirPlay in Ventura 13.3.1

### ISSUE THREAD

**Issue by gtrooper** [zearp/Nucintosh#131]
Hi @zearp ! I cant make Airplay Work in Ventura 13.3.1 using original NUC Intel WiFi and BT ! Do you know why it does not work ? I had it working perfectly in Monterey ! Thanks, in advance !

**Comment by zearp** [comment]
Do you mean AirPlay to Ventura as receiver or from Ventura to an AirPlay device? Both are not working for me on Ventura and to be honest I don' think I have tried it on Monterey.

A guess would be that the FeatureUnlock driver we use to unlock such things no longer works in Ventura and/or the Intel wireless/bluetooth in Ventura needs even more fixes. The people behind the Intel drivers focus mainly on wireless and not so much on the continuity features which AirPlay is part of. Those things like copy and pasting between iCloud devices and such is and was hit or miss with Intel hardware.

I will look into it but it is difficult to debug these things as there is iCloud magic involved. Log files are not very useful too unfortunately. AirPlay devices on the network advertise themselves. So either we can see them on Intel or we can't. I can't see my AirPlay speaker on Intel + Ventura. But why I wouldn't know.

Like I said my best guess is either in the feature unlocked or Intel driver. Most likely the latter as it still needs Ventura fixes and improved support.

**Comment by zearp** [comment]
Do you mean AirPlay to Ventura as receiver or from Ventura to an AirPlay device? Both are not working for me on Ventura and to be honest I don't think I have tried it on Monterey.

A guess would be that the FeatureUnlock driver we use to unlock such things no longer works in Ventura and/or the Intel wireless/bluetooth in Ventura needs even more fixes. The people behind the Intel drivers focus mainly on wireless and not so much on the continuity features which AirPlay is part of. Those things like copy and pasting between iCloud devices and such is and was hit or miss with Intel hardware.

I will look into it but it is difficult to debug these things as there is iCloud magic involved. Log files are not very useful too unfortunately. AirPlay devices on the network advertise themselves. So either we can see them on Intel or we can't. I can't see my AirPlay speaker on Intel + Ventura. But why I wouldn't know.

Like I said my best guess is either in the feature unlocker or Intel driver. Most likely the latter as it still needs Ventura fixes and improved support.

**Comment by gtrooper** [comment]
I mean AirPlay To Ventura From Another Mac or iOS Device. It works in Monterey with both a nuc8 and a nuc10 with zero configuration … So maybe you are right that they need more time to develop the drivers for Ventura and implement them in FeatureUnlock. One thing I dont understand is (In the description of github in FeatureUnlock says this "Systems with 'kern.hv_vmm_present' set to as 1 (Ventura and newer)". Do you know if this is applied automatically to the machines which run Ventura or we need to add it manually as an argument ? Thanks again for your valuable contribution !

**Comment by zearp** [comment]
Ah, it only unlocks AirPlay to the machine not from it. From it should work out of the box if the wireless is supported properly. so this is an OpenIntelWirless related issue. Someone seems to have reported an issue related to it already. The devs replied that tis expected behaviour. So I guess we were lucky it worked in Monterey. Seems they have no inclination to fix this as they never expected it to work on Intel in the first place.

**Comment by zearp** [comment]
Ah, it only unlocks AirPlay to the machine not from it. From it should work out of the box if the wireless is supported properly. So this is an OpenIntelWirless related issue.

Someone seems to have reported an issue related to it already. The devs replied that tis expected behaviour. So I guess we were lucky it worked in Monterey. Seems they have no inclination to fix this as they never expected it to work on Intel in the first place.

**Comment by Lorys89** [comment]
AirPlay With wifi intel works on sonoma. Tested and it works.

**Comment by koolwiki** [comment]
> AirPlay With wifi intel works on sonoma. Tested and it works.

Do you mean AirPlay to Sonoma as receiver?
