### ISSUE TITLE
Updating from MacOS 12.0.1 to MacOS 13

### ISSUE THREAD

**Issue by plix-xyz** [zearp/Nucintosh#133]
Hi @zearp, this is not an issue per se, so please take your time to reply. Also, thank you for maintaining this repo, I've used your EFI on my nuc and it is working great!

I'm currently on a very old release of the EFI, and on macOS 12.0.1. What would be the correct way to update both the EFI as well as macOS? Would I first follow the "Update" section of the readme to update the EFI, and then update the OS to 13 normally using the system-provided OTA update?
Thanks again!

**Comment by zearp** [comment]
Yes, use the latest release and rename the old folder to EFI.old as backup. Then start t he installer which will reboot when needed and use the newer EFI once it boots. 

I do suggest making and testing a bootable backup with your current install plus EFI. SuperDuper does this for free. Just in case something happens you can just boot into your old fully working install to fix things.

Personally I use old sata ssds for thisenkid if backups. It’s a perfect solution with usb 3 being fast enough for a non-aggravating desktop experience. Heck, the usb ports on the nuc all do 10gbit whereas sata maxes out at around 6gbit. 

Good luck!

**Comment by zearp** [comment]
On my Dell the OTA updates sometimes fail and it will download the full 12GB installer. When it does that I recommend canceling it and creating a new full installer yourself. Then put the new EFI on the installer and install on top of the old version (it won't delete your stuff). But I do that mainly because my download speeds are not great and if it downloads the full installer for an OTA I might as well do it myself and have an offline installer I can use on other machines.

**Comment by zearp** [comment]
On my Dell machines OTA updates sometimes fail and it will download the full 12GB installer. When it does that I recommend canceling it and creating a new full installer yourself. Then put the new EFI on the installer and install on top of the old version (it won't delete your stuff). But I do that mainly because my download speeds are not great and if it downloads the full installer for an OTA I might as well do it myself and have an offline installer I can use on other machines.
