### ISSUE TITLE
Question about CPUFriend

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#134]
Hey,

In your tutorial you mention "The default kexts provided give you the best performance and still lowers the lowest clock speed to 800mhz".

I noticed that TDP-down for my i7-8559u is 1.9GHz

(Intel documentation only provides LFM of 600MHz for a 4-core CPU with base freq. of 2.3GHz, so for a 4-core CPU with base frequency of 2.7GHz it is probably safe to assume LFM of 800MHz). 

**1. Can I try and raise the settings to something higher?** 

**2. How would I obtain the "default" settings for my CPU? Is it enough just to remove the CPUFriend... kexts and do a clean config.plist snapshot?**

The reason I ask is because I occasionally get animation stutter on my monitor and I've isolated every other possible cause, the only thing I'm left with is the CPU/iGPU not catching up quickly enough.

**Comment by zearp** [comment]
I don't think there such a thing as defaults as the OS always does some kind of pwoermanagement. Even chasing the SMBIOS can result in higher/lower clock speeds.

If I were you I would experiment and see what works. You don't have to use CPUFriend and/or you can maker your own config and see how that works out. Just set the two kexts as disabled in the config and reboot, they won't be loaded and you egt the default power management Apple sets for this SMBIOS. The i5 models have the same CPU as the 2018 MacBook Pro. You could try that SMBIOS but in my testing I got display issues. But we do have a mobile platform in the NUC.

With no kexts you get what the macOS kernel wants, which depends on the SMBIOS used. For example on my older Dell build charging the SMBIOS would change the base clocks of the iGPU. Sometimes double the stock base clock.

I don't know which modes all the cpu;'s support, it can differ between models. I did upload the 7th gen spec but haven;'t gotten time to dive into that and not planning to do so either in the short term.

https://github.com/zearp/Nucintosh/blob/master/Stuff/8th%20gen%20datasheet.pdf

I'm curious to what your experiments will lead to.

I've not had any of there issues you describe. The stuttering could have many causes. Can you reproduce it? If so then I can try to reproduce it too but otherwise it will be super difficult to fix that. There are simply too many variables.

**Comment by naryfa** [comment]
OK, I appreciate your input. Valuable info.

I have now disabled the CPUFriend and CPUFriendDataProvider.

Watching the clocks in the Intel Power Gadget I see it mostly idles at 1.2GHz. Occasionally it will drop below or go above, but comes back to 1.2GHz almost instantly. I think I prefer this, because the passive case seems to be dealing with the heat easily. 

Image if you're curious.
![Screenshot 2023-08-18 at 1 43 48 PM](https://github.com/zearp/Nucintosh/assets/38587586/2e6b8fc3-98b9-4fd2-b401-4b4cb4ef3b4f)

Regarding the documentation, I saw yesterday something similar to what you have on 8th & 9th gen CPUs, where I found LFM for the CPUs I mentioned. Starts on page 98 of the document:

https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/8th-gen-core-family-datasheet-vol-1.pdf
