### ISSUE TITLE
> @Lorys89 Feel free to share.

### ISSUE THREAD

**Issue by Lorys89** [zearp/Nucintosh#137]
Send me your acpi origin Or sysreport and ioreg log

**Comment by Lorys89** [comment]
Can I apply the changes to your efi release?

**Comment by Lorys89** [comment]
if you have nuc8 try this efi  https://file.io/x9oPBXBhU8qS
if you have nuc10 sen me ioreg log and sysreport

**Comment by zearp** [comment]
Not sure what you want me to do. The ACPI patch is one big file with all separate patches merged. I have no time to dissect it and figure out whats needed to make hot plug work and I also can't test it as I don't have any TB devices here right now. I guess the best I can do is boot the EFI and see if the icon is gone and how TB is appearing. But I'd like some details on whats changed and why.

**Comment by Lorys89** [comment]
Analyze the ssdt file and what you do not understand I'll explain it to you

**Comment by zearp** [comment]
If you want me to make any changes submit a proper PR or at the very least explain whats wrong or needs to be changed in the current EFI. Personally I don't care much about hot plug or some icon being there or not. Thanks though.

**Comment by Lorys89** [comment]
Send an ioreg log with your current efi and so I'll explain everything, first understand the changes and then I can do a pr if you want.

**Comment by Lorys89** [comment]
In your current efi you don't even turn off H_EC
So only improvements I can make, I have 2 nuc8 and Thunderbolt dock and hotplug tests always give positive results, it works hot and cold and after sleep.

**Comment by Lorys89** [comment]
![Screenshot 2023-09-05 alle 15 51 00](https://github.com/zearp/Nucintosh/assets/64613690/dcfb6de8-197a-4068-b275-b5461a16d685)
[Mac mini.zip](https://github.com/zearp/Nucintosh/files/12524414/Mac.mini.zip)

**Comment by zearp** [comment]
This is not how you help and improve a project. You just give me some kind of homework with a giant merged ACPI patch mess for me to dissect and even tell me to tell you when I understand the changes before you send a PR or any explanations. Smh. 

I'm perfectly happy with the current state of the EFI. I'm not going to spend time figuring out what you did. You can either just tell me or don't. Since you don't want to provide a PR or anything useful there's no point to continue this conversation.
