### ISSUE TITLE
Animation stutter on Ventura with SmoothScroll

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#149]
Hey Zearp,

I wanted to pick your brains on this one a little. 

I am still getting the scroll stutters and can't pinpoint what is causing it. I have updated the HDMI firmware (like you pointed out on the main page), but it hasn't changed anything.

I'm wondering if the Intel 655 iGPU is simply too weak for Ventura, but things just don't add up.

If I scroll pages with a keyboard, the scroll behaves super-smoothly, if I use the mouse (regardless of type) it stutters on animation. I tried this with [SmoothScroll](https://www.smoothscroll.net/mac/) and with [MOS](https://mos.caldis.me/), I tried with different mice, I tried with different HDMI cables and can't figure out what's causing it. Even wrote the developer of SmoothScroll to see if he has any problems with the newer macOS versions.

Tried looking at Intel Power Gadget to see how the iGPU performs and nothing seems out of the ordinary, other than it parks itself when not in use (but I guess that's by macOS design). I also disabled transparency in Accessibility settings, tried reducing motion as well. Nothing helps.

The BIOS graphics is set to high performance (If I remember the setting's name correctly) and of course it's on the fanless profile. 

I tried using Magic Mouse and didn't see any stutter, but can't use it because of how painful to my hands it simply is. Just as a trackpad, it requires the wrist to be somewhat semi-suspended above the control surface. 

I'm pulling my hair and don't know where to look anymore. 

Of course you may close this issue, but would love to hear if you have an idea what could I possibly try to remedy the stutters. 

I realize it's a low importance to some, but drives me nuts when every other scroll just starts to lag and micro-jump.

My exact cpu is i7-8559u with Intel 655 on this NUC.

I'm almost keen on believing this iGPU can't simply keep up with the demand at this point.

**Comment by zearp** [comment]
Unfortunately this is by design, which is confirmed by everything being fine as you want it when using an Apple mouse. And yes those have the worst ergonomics ever. Plus you can't charge it and use the mouse at the same time. I do really like Apple's touchpad but thats not a proper replacement.

Pretty much all 3rd party mice will have that issue. It is not something we can with in the EFI, you could 'hack' your mouse and change the vendor and device id but that might brick the mouse if possible at all. Some tools will fix or make it better for certain brands. You'll have to experiment and see what works best. If you have Xcode installed you can try compiling this control panel and see if those options work on your mouse.

https://github.com/marv-in-k/Scrollify

**Comment by zearp** [comment]
Unfortunately this is by design, which is confirmed by everything being fine as you want it when using an Apple mouse. And yes those have the worst ergonomics ever. Plus you can't charge it and use the mouse at the same time. I do really like Apple's touchpad but thats not a proper replacement.

Pretty much all 3rd party mice will have that issue. It is not something we can fix with in the EFI. You could 'hack' your mouse and change the vendor and device id to match that of an apple mouse. But that might brick the mouse if possible at all.

Some tools will fix or make it better for certain brands. You'll have to experiment and see what works best. If you have Xcode installed you can try compiling this control panel and see if these smooth scroll options work on your mouse.

https://github.com/marv-in-k/Scrollify

**Comment by naryfa** [comment]
I'll check out the panel. Thank you so much for this input. 

I do agree, people are beginning to say on forums that Apple designs everything in such a way, that literally forces people to buy nothing else, but Apple. 

I know it's nothing new, but it is going to such an extreme that I see people becoming extremely frustrated as they begin to feel they're in a jail cell.

Apple's paranoid control of everything will form cracks at some point.
