### ISSUE TITLE
Remove express card icon failed

### ISSUE THREAD

**Issue by chfight** [zearp/Nucintosh#15]
`sudo mount -uw /` run error.

When I run the command and input password, return `mount_apfs: volume could not be mounted: Permission denied` and `mount: / failed with 66` error to me.

System version is big sur 11.01.

Is there a solution?

**Comment by antoninchadima** [comment]
@chfight this happens on Big Sur? Am I right?

**Comment by chfight** [comment]
@antoninchadima Yes，it only happens on Big Sur. No problem on Catalina.

**Comment by chfight** [comment]
Sorry, I saw a solution to this error that I didn't find before

**Comment by zearp** [comment]
The solution I mentioned [here](https://github.com/zearp/Nucintosh#big-sur) didn't work? Please let us know what you did to fix it as it may help others. Thanks!

**Comment by antoninchadima** [comment]
- The section Big Sur https://github.com/zearp/Nucintosh#big-sur doesn't mention any procedure for removing the express card icon.
- The section Post-install https://github.com/zearp/Nucintosh#post-install says:
`Remove express card icon: Run sudo mount -uw / && killall Finder && sudo mv /System/Library/CoreServices/Menu\ Extras/ExpressCard.menu /System/Library/CoreServices/Menu\ Extras/ExpressCard.menu.bak && sudo touch /System/Library/CoreServices/Menu\ Extras/ExpressCard.menu`
 **But this isn't working on Big Sur.**
- Maybe, you have to disable SIP first... But this should be explicitly mentioned in the section Big Sur (and the special way for disabling SIP - I suppose that recovery and csrutil aren't enough).

**Comment by zearp** [comment]
@antoninchadima It doesn't mention it cuz the procedure is the same for all macOS versions. SIP is disabled by default for Catalina and the Big Sur section mentions how to disable it in Big Sur. Maybe I should clarify SIP needs to be disabled to remove the icon but this is kind of a given since you need it disabled to get full access to your filesystem and SIP is disabled in my config when installing Catalina. I don't recommend using Big Sur as daily driver for the time being.

**Comment by zearp** [comment]
Hopefully this clarifies things; https://github.com/zearp/Nucintosh/commit/520d7e6d8dbe1f010fd538a96f2301fbb84c2077
