### ISSUE TITLE
NUC8i7BEH Aux not working

### ISSUE THREAD

**Issue by michaelclaw** [zearp/Nucintosh#153]
I inserted an AUX cable into the front of the unit to my bose soundbar and Sonoma detected headphones were plugged in but not audio could be played through them.

Build: NUC8i7BEH runnning latest EFI release on Sonoma 14.4.1

This was tested on a fresh install, no changes have been made to the EFI or config other than what is in your guide.

I would prefer to purchase a bluetooth dongle to connect the soundbar but I'm not very experienced with modifying the EFI/Kexts. I would appreciate it if you could make a guide on how to setup the OS post-install for a usb BT dongle too.

**Comment by zearp** [comment]
Sorry but I can't reproduce it. When I plug in headphones in the front audio plays starts playing there. Sometimes it is needed to manually change the active audio output but most of there it auto detects atone you insert the cable and switches audio to that output.

There are usb bluetooth dongles that work out of the box in macOS, you don't need to modify anything apart from maybe mapping the usb port you plug the dongle into a internal if you get any sleep issues. I purchased a few of these dongles on Amazon and they worked without having to modify any kexts. They were sold a "csr" 4.0 bluetooth dongle or something like that. I can lookup the device and vendor id's but not sure if that would help you find the same dongle.

**Comment by zearp** [comment]
Sorry but I can't reproduce it. When I plug in headphones in the front audio plays starts playing there. Sometimes it is needed to manually change the active audio output but most of the time it auto senses when you insert the cable and switches audio to that output automatically.

There are usb bluetooth dongles that work out of the box in macOS, you don't need to modify anything apart from maybe mapping the usb port you plug the dongle into a internal if you get any sleep issues. I purchased a few of these dongles on Amazon and they worked without having to modify any kexts. They were sold a "csr" 4.0 bluetooth dongle or something like that. I can lookup the device and vendor id's but not sure if that would help you find the same dongle.

**Comment by zearp** [comment]
Sorry but I can't reproduce it. When I plug in headphones in the front audio starts playing there. Sometimes it is needed to manually change the active audio output but most of the time it auto senses when you insert the cable and switches audio to that output automatically.

There are usb bluetooth dongles that work out of the box in macOS, you don't need to modify anything apart from maybe mapping the usb port you plug the dongle into a internal if you get any sleep issues. I purchased a few of these dongles on Amazon and they worked without having to modify any kexts. They were sold a "csr" 4.0 bluetooth dongle or something like that. I can lookup the device and vendor id's but not sure if that would help you find the same dongle.

**Comment by michaelclaw** [comment]
Hey thank you for the reply,

I believe it did auto sense on mine too and switch to the headphones automatically. I will have to try some regular headphones and see if those will work today.

I will order one of the usb bt dongles on Amazon and try that too. Thanks again for the EFI, install was smooth on both of my nuc8s

**Comment by zearp** [comment]
Is there a reason you're not using the Intel bluetooth? I checked my dongles and they all have [this](https://www.qualcomm.com/products/technology/bluetooth/csr8510) chipset and worked out of the box in Sonoma and older. Also works on my NUCs after disabling the builtin module. When running ```lsusb``` it shows up like this:

```
Bus 020 Device 001: ID 0a12:0001 Cambridge Silicon Radio Ltd. CSR8510 A10 
```

Some of these dongles with similar chipsets will work too but you'll have to either the device and vendor id on the dongle itself (tricky) or edit a plist file add the the vender/device id of the dongle.

**Comment by zearp** [comment]
Is there a reason you're not using the Intel bluetooth? I checked my dongles and they all have [this](https://www.qualcomm.com/products/technology/bluetooth/csr8510) chipset and worked out of the box in Sonoma and older. Also works on my NUCs after disabling the builtin module. When running ```lsusb``` it shows up like this:

```
Bus 020 Device 001: ID 0a12:0001 Cambridge Silicon Radio Ltd. CSR8510 A10 
```

Some of these dongles with similar chipsets will work too but you'll have to either change the device and vendor id on the dongle itself (tricky) or edit a plist file add the the vender/device id of the dongle.

**Comment by michaelclaw** [comment]
I am using the intel bluetooth, when it works right now. It seems like upon boot it will connect to my soundbar but it will randomly just stop working and will disable itself in the settings or still show active (BT) and wont connect to anything. It does this consistently to the point that I'd rather buy a separate module or use aux.
I didn't bring up the intel issue since you stated on the guide that there are connection issues so i thought it was a known problem.

**Comment by zearp** [comment]
Bluetooth is flaky even on my real Macs, it is a feature I think. What you can try is adding another kext, it shouldn't be needed but it might help in your case. I have a Keychron bluetooth keyboard that can connect up to 3 devices, 2 of them are real Macs and I have disconnects every now and then on all 3 machines. Same for the mice. I went all dongle and wired for those cuz it was very annoying.

[IntelBTPatcher.kext.zip](https://github.com/zearp/Nucintosh/files/14891800/IntelBTPatcher.kext.zip)

What I noticed on my other builds is that without that kext sometimes bluetooth simply doesn't work, but never that it just stops working. I think it has to do with the firmware inside the bluetooth module. When I boot into Linux or Windows sometimes booting back into macOS results in panic, boot loop or non working bluetooth because of the loaded firmware. Powering down fixes it. But that might be something completely different from your issue.

Have you checked the logs when the disconnects happen? Might be a long shot but sometimes the logs can be helpful pinpointing a cause.

**Comment by michaelclaw** [comment]
Honestly this is my first working hackintosh/macos so I'm not sure where to look for the logs. I'm using all USB for the keyboard/mouse and only running macos so no dualboot. I will google how to check the logs and i'll report back.

**Comment by zearp** [comment]
The easiest way to access the logs is to use the ```Console``` app and the ```log``` command in the terminal. The former has a mixed bag and the latter is mostly system logs best searched in conjunction with grep and an additional kext called DebugEnhancher to get more usable output. I would try the Console app first if the problems persist after adding the IntelBTPatcher kext.

Good luck and congrats on your first macOS install!

**Comment by michaelclaw** [comment]
So I have been trying to reproduce it but since I posted the issue thread here It's been connecting no problem so I'm not really sure what it is. I haven't added the kext yet either. I will keep running it how it is and if the issue pops up again I'll check the console logs.

On a separate note, I'm not sure If I should create a separate issue but I believe the SATA kext isn't included with the EFI. I get the stop sign startup error when booting. My sata drive is only for data and is empty right now and I'm booting off a NVME.

**Comment by zearp** [comment]
I have no idea what you mean with "the sata kext" because there is no need for any sata kexts or any other additional kexts whatsoever. Even that extra bt kext I posted is not really needed but *might* help you with your odd issue.

I have been using both nvme and sata drives in my NUCs for over 4 years now, some even have both. Never seen a stop sign or had any issues related to sata/nvme. I don't know why you get a stop sign, I would need more details and a way to reproduce it.

At the very least I need a panic log and/or boot log regarding the stop sign. There is nothing I can do other than guess if I can't reproduce the issue here.

**Comment by michaelclaw** [comment]
I assumed there was a sata kext or something, I was having that issue and just guessed it was the sata drive so I disabled it in bios and it booted instantly.

I have the logs from this command log show --last boot --predicate 'process == "kernel"'
 Would this be helpful? I'm looking through it but it's a giant log

**Comment by zearp** [comment]
Those logs aren’t useful in this case as the stop sign, I assume it happens very quickly when booting. You have verbose boot enabled?  I would film the screen at the highest fps tour phone can handle that’s still 1080p or better. Then see the last text before the stop sign. You may also need to use debug version of OpenCore and some kexts if not enough info is showing. Personally I don’t think what you experience is caused by the EFI but if you can provide me more info we can try to figure it out. If it’s a really new install with not much to lose I suggest maybe starting fresh.

**Comment by zearp** [comment]
Those logs aren’t useful in this case as the stop sign, I assume it happens very quickly when booting. You have verbose boot enabled? I would film the screen at the highest fps tour phone can handle that’s still 1080p or better. Then see the last text before the stop sign.

You may also need to use debug version of OpenCore and some kexts if not enough info is showing. Personally I don’t think what you experience is caused by the EFI but if you can provide more info we can try to figure it out. If it’s a really new install with not much to lose I suggest maybe starting fresh.

You can copy your settings etc back to a fresh macOs install using the migration assistant if you make a backup of the current install.
