### ISSUE TITLE
microSD not working on 14.7

### ISSUE THREAD

**Issue by mcinp** [zearp/Nucintosh#164]
I've been using my NUC with versions up to 14.3.1 with zearp/Cucintosh EFI from January and I was able to use microSD card reader both inside macos and to install macOS.
Recently I reinstalled with latest EFI and macOS 14.7 and miscroSD card reader doesn't work anymore.  Under macOS inserted card is not visible.
Still works on Windows.

**Comment by zearp** [comment]
The kexts have been disabled but not removed, should be a matter of enabling them again n your config. This was done because of kernel panics it can cause and the fact the person who made those drivers is no longer updating them for newer macOS versions.

You need to enable these two kexts:

https://github.com/zearp/Nucintosh/blob/master/EFI/OC/config.plist#L573-L608

Good luck!

**Comment by zearp** [comment]
The kexts have been disabled but not removed, should be a matter of enabling them again in your config. This was done because of kernel panics it can cause (rarely) and the fact the person who made those drivers is no longer updating them for newer macOS versions.

You need to enable these two kexts:

https://github.com/zearp/Nucintosh/blob/master/EFI/OC/config.plist#L573-L608

Good luck!

**Comment by mcinp** [comment]
Oh thanks for the explanation !
