### ISSUE TITLE
[BUG] Doesn't event boot to open core menu

### ISSUE THREAD

**Issue by cabiamdos** [zearp/Nucintosh#165]
Please provide the follow information:

Hello,
I have been trying to set up macos with your guide but doesn't work.
My computer is intel nuc 8 i3.
Steps:
1. rufus -> format non bootable fat32
2. download macos recovery with the use (https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html#downloading-macos) and place the generated folder `com.apple.recovery.boot` inside the bootable usb created from rufus. Download the macos sequoia

```
# Latest version
# ie. Sequoia (15)
py macrecovery.py -b Mac-937A206F2EE63C01 -m 00000000000000000 download
```
3. download the latest EFI FILE (https://github.com/zearp/Nucintosh/releases/tag/v5.4) from here.
4. edit the config.plist replacint the following values:
```
<dict>
			<key>AdviseFeatures</key>
			<false/>
			<key>MLB</key>
			<string>C07229500GUKXPGJC</string>
			<key>MaxBIOSVersion</key>
			<false/>
			<key>ProcessorType</key>
			<integer>0</integer>
			<key>ROM</key>
			<data>Hk85urAJ</data>
			<key>SpoofVendor</key>
			<false/>
			<key>SystemMemoryStatus</key>
			<string>Auto</string>
			<key>SystemProductName</key>
			<string>Macmini8,1</string>
			<key>SystemSerialNumber</key>
			<string>C07J30DPJYVX</string>
			<key>SystemUUID</key>
			<string>3FB0E0E6-26BF-465C-AA7C-4FFCB5373EEC</string>
		</dict>
```
5. Boot the machine, after booting nothing happens.

- Steps to reproduce the issue -- this is crucial
- macOS version and optionally the build number
- Any changes you made to the config and/or EFI other than serials/etc
- Any logs related to the issue if applicable

**Comment by zearp** [comment]
I have never used the recovery install methods because I prefer full installers. I do know that the EFI is just that, an EFI. If you made the installer correctly it should at the very least show the OpenCore picker menu. Even without anything else on the stick.

My guess is you copied the EFI on the wrong partition of the installer. If you are certain you made your installer correctly then you can format another usb stick as FAT32 and copy the EFI folder the root and boot form that. The OpenCore picker menu will show and if it detects the macOS installer you made you can boot into it.

I don't support or have ever even dabbled with the recovery install method myself and not going to try it for this issue as I'm sure the EFI will boot fine as long as the installer usb has an EFI partition. I know it boots the same as the full installer. It just downloads the files instead of having them already.

Try making the installer in macOS, be it another hack, a VM or a Mac and I am 100% certain it will boot just fine, if it wouldn't many more issues would've been opened. It is not difficult to setup a macOS VM and create a full installer. I've used [this](https://github.com/notAperson535/OneClick-macOS-Simple-KVM) project in the past with success when I had no working hack or Mac. You don't need full graphical acceleration to make the full installer or even the latest macOS. You can make a Sequoia installer on a Monterey VM and older will probably work too.

Good luck!
