### ISSUE TITLE
Intel iGPU only take 7MB

### ISSUE THREAD

**Issue by hitman3r44** [zearp/Nucintosh#19]
Thanks for the project. I installed BigSur but Intel iGPU only take 7MB of Ram, where I installed Catalina it takes 2GB of Ram. Is there anything I need to tweak.
![IMG_20201230_151640](https://user-images.githubusercontent.com/3492827/103392302-1d0b9380-4aeb-11eb-96c2-3b6832a2fec1.jpg)

**Comment by zearp** [comment]
Looks like something has changed in the updates that broke the frame buffer settings. Cuz it shows a 640 instead of 655. I assume you didn’t change anything in the config. I tested it on the final release and it was working ok there. 

The 655 is natively supported so its weird it reports it wrongly. I don’t use any device id spoofing for that reason. What’s your NUC model number? Maybe some NUC8 Coffee Lake models have a different Iris model but I don’t think they do.  

I will try with the latest 11.1 release next year and see how it goes. Thanks for letting me know.

**Comment by zearp** [comment]
What’s your NUC model?

The only NUC I can find with an Iris 640 is a NUC7.  I don’t use decide id spoofing since the 655 is natively supported and only needs some config to sort out the connectors and expand the VRAM a bit.

**Comment by zearp** [comment]
What’s your NUC model?

The only NUC I can find with an Iris 640 is a NUC7.  I don’t use device id spoofing since the 655 is natively supported and  just needs some config entries to sort out the connectors and expand the VRAM a bit.

The 2018 MacBook Pro and Mac mini have the Iris 655.

**Comment by zearp** [comment]
What’s your NUC model?

Cuz your picture shows an Iris 640 instead of 655. The only NUC I can find with an Iris 640 is a NUC7. Your memory speed is also displayed incorrectly if you are using a NUC8 but correct if you're using a NUC7.

I don’t use device id spoofing since the 655 is natively supported and just needs some basic config entries. The 2018 MacBook Pro and Mac mini have the Iris 655.

**Comment by zearp** [comment]
What’s your NUC model?

Cuz your picture shows an Iris 640 instead of 655. The only NUC I can find with an Iris 640 is a NUC7. Your memory speed is also displayed incorrectly if you are using a NUC8 but correct if you're using a NUC7. Same for the processor. It should display an i5 quad core not dual core. I think you're using a NUC7 which isn't supported by this config.

Funny it worked sort of ok in Catalina, given all the NUC8 specific ACPI patches and such. The NUC7 will run both fine though, but please don't use this config cuz it's not optimised and might cause issues in the long run.

I don’t use device id spoofing since the 655 is natively supported and just needs some basic config entries. The 2018 MacBook Pro and Mac mini have the Iris 655.

**Comment by zearp** [comment]
What’s your NUC model? It appears you're using a NUC7.

Your picture shows an Iris 640 instead of 655 and the memory speed is also displayed incorrectly if you are using a NUC8 but correct if you're using a NUC7. Same for the processor, it should display an i5 quad core not dual core. I think you're using a NUC7 which isn't supported by this config.

Funny it worked sort of ok in Catalina, given all the NUC8 specific ACPI patches and such. The NUC7 will run both fine though, but please don't use this config cuz it's not optimised and might cause issues in the long run.

**Comment by zearp** [comment]
Just did a clean install of Big Sur 11.1 and everything looks good here.

![Screenshot 2020-12-31 at 12 48 18](https://user-images.githubusercontent.com/63272687/103409339-a2805980-4b66-11eb-9271-fb5e7ee93d64.png)

**Comment by zearp** [comment]
Just did a clean install of Big Sur 11.1 on my test NUC and everything looks good.

![Screenshot 2020-12-31 at 12 48 18](https://user-images.githubusercontent.com/63272687/103409370-ccd21700-4b66-11eb-9212-7ef996c20bcf.png)

**Comment by cangurellobello** [comment]
> Just did a clean install of Big Sur 11.1 on my test NUC and everything looks good.
> 
> ![Screenshot 2020-12-31 at 12 48 18](https://user-images.githubusercontent.com/63272687/103409370-ccd21700-4b66-11eb-9212-7ef996c20bcf.png)

Weird, mine is displaying less mem too
![Schermata 2021-06-27 alle 20 09 44](https://user-images.githubusercontent.com/60691013/123555061-a68edc00-d783-11eb-8e5b-fca52ae5e8ee.png)

**Comment by zearp** [comment]
It's because I removed the 2gb VRAM settings as the documentation states its best to not use it. So now macSO decides how much to allocate, which is 1.5gb on most systems. I think it gets reduced if you have 4gb ram and maybe increased if you got 23gb or more, not sure though.

If you want the 2gb VRAM back you will need to add a ```framebuffer-unifiedmem``` entry with as data field ```00000080``` to the frame buffer config. 

From the WhateverGreen FAQ:
> framebuffer-unifiedmem (VRAM, it is not recommended to use this patch)

I still have it in my other repo though, which reminds me to remove it there too lol.
