### ISSUE TITLE
Postinstall question - unknown EFI content

### ISSUE THREAD

**Issue by stschulze1972** [zearp/Nucintosh#21]
```
NUCmini ~ % sudo diskutil list               
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk0
   1:                        EFI ⁨EFI⁩                     209.7 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk1⁩         1000.0 GB  disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1000.0 GB  disk1
                                 Physical Store disk0s2
   1:                APFS Volume ⁨BigSur - Data⁩           18.1 GB    disk1s1
   2:                APFS Volume ⁨Preboot⁩                 293.5 MB   disk1s2
   3:                APFS Volume ⁨Recovery⁩                613.6 MB   disk1s3
   4:                APFS Volume ⁨VM⁩                      1.1 MB     disk1s4
   5:                APFS Volume ⁨BigSur⁩                  15.0 GB    disk1s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 15.0 GB    disk1s5s1

```

`sudo diskutil mount /dev/disk0s1`

```
NUCmini ~ % ls -l /Volumes/EFI/EFI
total 4
drwxrwxrwx  1   staff   512  3 Jan 01:56 APPLE
drwxrwxrwx  1   staff   512  3 Jan 03:12 BOOT
drwxrwxrwx  1   staff  1024  3 Jan 03:12 OC
```

**APPLE-Content .....nedd to delete these files?**

NUCmini ~ % ls -l /Volumes/EFI/EFI/APPLE/UPDATERS/MULTIUPDATER/*
-rwxrwxrwx  1   staff  134304  3 Jan 01:56 /Volumes/EFI/EFI/APPLE/UPDATERS/MULTIUPDATER/DpUtil.efi
-rwxrwxrwx  1   staff    3744  8 Dez 07:17 /Volumes/EFI/EFI/APPLE/UPDATERS/MULTIUPDATER/DpUtil.efi.j174ap.im4m
-rwxrwxrwx  1   staff  524402  3 Jan 01:56 /Volumes/EFI/EFI/APPLE/UPDATERS/MULTIUPDATER/MCDP29xxApp_V2.025.bin
-rwxrwxrwx  1  staff   18490  3 Jan 01:56 /Volumes/EFI/EFI/APPLE/UPDATERS/MULTIUPDATER/MCDP29xxIsp_V1.10.bin
-rwxrwxrwx  1   staff  102968  3 Jan 01:56 /Volumes/EFI/EFI/APPLE/UPDATERS/MULTIUPDATER/MultiUpdater.efi
-rwxrwxrwx  1   staff    3744  8 Dez 07:17 /Volumes/EFI/EFI/APPLE/UPDATERS/MULTIUPDATER/MultiUpdater.efi.j174ap.im4m
`

**Comment by zearp** [comment]
There is no need to delete the Apple folder that macOS can create with firmware updates. Those won't be applied due to ```BlacklistAppleUpdate``` being set to true. But you can delete the folder if you want and free up a little space.

Please keep in mind the issue section is not for support but merely for reporting bugs and errors in the repo and of course to contribute fixes or optimisations. I assume everybody using this has read the [Dortania](https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html) guide and [OpenCore](https://github.com/acidanthera/OpenCorePkg/raw/master/Docs/Configuration.pdf) documentation.
