### ISSUE TITLE
BCM943224PCIEBT2 support

### ISSUE THREAD

**Issue by laradvance** [zearp/Nucintosh#22]
Can you explain in details how to make BCM943224PCIEBT2 work on big sur?
Thanks

**Comment by zearp** [comment]
In short you have to enable the "whitelist" patch in the config and then replace IO80211Family.kext with one from an older macOS version, like Catalina or Mojave. There are multiple ways to replace system kexts in Big Sur.

Something like [this](https://github.com/chris1111/Kext-Droplet-Big-Sur) may also work but I have not tested it. There are multiple methods to add the older IO80211Family.kext to the system. Which method you want to use is really up to you.

One way to go and that I personally tested is to patch your installer usb stick with [Big Sur micro patcher](https://github.com/barrykn/big-sur-micropatcher). Simply download or clone that repo and run ```./micropatcher.sh``` from its folder in the terminal. Then once the installer is patched and without booting into it run ``` /Volumes/Install\ macOS\ Big\ Sur\ Beta/patch-kexts.sh --2012```.

You may have to remove the [model check](https://github.com/barrykn/big-sur-micropatcher/blob/main/payloads/patch-kexts.sh#L197-L284) from the shell script if it says you model is already supported. Comment out or delete the highlighted text. Once those checks are removed it will install the kexts just fine.

You will also need to set ```SecureBootModel``` to disabled in the config or else it keeps booting into recovery. Once it's all done reboot and clear NVRAM. After that Big Sur will boot up fine and your wifi will work. On mine I had to manually add it in ```System Preferences -> Network```. Press the little ```+``` button and add the wifi thats listed in there.

This will run all the commands for you instead of you having to do it manually. But you can of course look which commands the script executes and run them yourself if you prefer doing it manually. I might add those steps at one point when boredom strikes.

I can confirm the micro-patcher method works great on Big Sur 11.1 and the BCM943224PCIEBT2 from my old MacBook Air lives to serve another day.

**Comment by zearp** [comment]
In short you have to enable the "whitelist" patch in the config and then add and/or replace IO80211Family.kext with one from an older macOS version, like Catalina or Mojave. Those kexts can be found on the Big Sur micro patcher repo, see below.

Something easy and simple like [this](https://github.com/chris1111/Kext-Droplet-Big-Sur) may work but I have not tested it. There are multiple methods to add an older IO80211Family.kext to the system. Which method you want to use is really up to you.

One way to go and that I personally tested is to patch your installer usb stick with [Big Sur micro patcher](https://github.com/barrykn/big-sur-micropatcher). I prefer using the patcher because it's just a collection of shell scripts that execute commands for you. Simply download or clone their repo and run ```./micropatcher.sh``` from its folder in the terminal. Then once the installer is patched and without booting into it run ``` /Volumes/Install\ macOS\ Big\ Sur/patch-kexts.sh --2012```.

You may have to remove the [model check](https://github.com/barrykn/big-sur-micropatcher/blob/main/payloads/patch-kexts.sh#L197-L284) from the shell script if it says your model is already supported. Comment out or delete the highlighted text. Once those checks are removed it will install the kexts just fine.

You will also need to set ```SecureBootModel``` to disabled in the config or else it keeps booting into recovery. Once it's all done reboot and clear NVRAM. After that Big Sur will boot up fine and your wifi will work. On mine I had to manually add it in ```System Preferences -> Network``` then press the little ```+``` button and add the wifi thats listed in there.

The patcher will run all the commands for you instead of you having to do it manually. But you can of course look which commands the script executes and run them yourself if you prefer doing it manually or want to learn more. I might add those steps at one point when boredom strikes.

I can confirm the micro-patcher method works great on Big Sur 11.1 and the BCM943224PCIEBT2 from my old MacBook Air lives to serve another day.

**Comment by laradvance** [comment]
Thanks
