### ISSUE TITLE
Audio Volume an HDMI

### ISSUE THREAD

**Issue by stschulze1972** [zearp/Nucintosh#23]
NUC is connected to HDMI in Samsung Syncmaster Monitor

Audio over HDMI is working, but Vol+ and Vol- are not working.

Volume must be set with Monitor remote

HDMI is displayed as Displayport ?!

**Comment by zearp** [comment]
I don't think volume control is supported over HDMI. Even on my MacBookI don't have volume control when using HDMI. The same happens when I use the digital output (SPDIF) on my MacBook. I think this is a macOS limitation.

Where do you see HDMI being shown as DisplayPort? Which port on the NUC are you using? I think the usb-c output only does DisplayPort. So I you connect a usb-c hub that has an HDMI port the DisplayPort signal is converted.

Please provide some more details.

**Comment by zearp** [comment]
I don't think volume control is supported over HDMI. Even on my MacBook I don't have volume control when using HDMI. The same happens when I use the digital output (SPDIF) on my MacBook. I think this is a macOS limitation.

Where do you see HDMI being shown as DisplayPort? Which port on the NUC are you using? I think the usb-c output only does DisplayPort. So I you connect a usb-c hub that has an HDMI port the DisplayPort signal is converted.

Please provide some more details.

**Comment by stschulze1972** [comment]
Where do you see HDMI being shown as DisplayPort? 

Audio Settings

**Comment by zearp** [comment]
I just confirmed my suspicion; there is no way to control any digital audio output volume in macOS. This applies to any digital audio, including HDMI and DisplayPort. This is a "limitation" of macOS Andorras a choice because the signal is digital. You control the volume in apps (if supported) or on the amp/speakers.

On mine it also shows DisplayPort when using usb-c or HDMI output. I don't think it is a problem though. It's just a visual thing. Maybe you can experiment with the connector settings in the frame buffer patch to have it show up how you want it to show. To me what matters is if it works or not, and it works as expected.

It doesn't bother me at all and it doesn't impede functionality either. It's pretty much just a visual thing and it might not even be possible to fix it. I'm not planning to invest time in this but you're free to open a PR if you find a way to make audio settings show the correct connector name.

The names might be due to FakePCIID.kext, try disabling that kext and then reconnect the cable once booted up and see what audio settings show. Without that kext audio over HDMI only works when you replug the cable manually after booting up. I have an open issue about it.

**Comment by zearp** [comment]
I just confirmed my suspicion; there is no way to control any digital audio output volume in macOS. This applies to any digital audio, including HDMI and DisplayPort. This is a "limitation" of macOS and/or a choice because the signal is digital. You control the volume in apps (if supported) or on the amp/speakers.

On mine it also shows DisplayPort when using usb-c or HDMI output. I don't think it is a problem though. It's just a visual thing. Maybe you can experiment with the connector settings in the frame buffer patch to have it show up how you want it to show. To me what matters is if it works or not, and it works as expected.

It doesn't bother me at all and it doesn't impede functionality either. It's pretty much just a visual thing and it might not even be possible to fix it. I'm not planning to invest time in this but you're free to open a PR if you find a way to make audio settings show the correct connector name.

The names might be due to FakePCIID.kext, try disabling that kext and then reconnect the cable once booted up and see what audio settings show. Without that kext audio over HDMI only works when you replug the cable manually after booting up. I have an open issue about it.
