### ISSUE TITLE
Netflix in Safari

### ISSUE THREAD

**Issue by SeaDaddytheRed** [zearp/Nucintosh#24]
First I just want to thank you for putting together this release for the NUC.  I also have the Akasa case and now have a silent "Macmini" that is running beautifully thanks to you!

My only problem so far is Netflix in Safari.   As far as I can tell from reading various tutorials on the net Safari 14 should be able to run Netflix on a hackintosh with an iGPU but for some reason Netflix always errors for me.  I get the S7706 error code when trying to play anything.

I can play it in any other browser but then it is stuck at 720p max because of DRM.

I am running Catalina now but I am keeping my hopes up for a Big Sur update here sometime!  Again, thank you for your work!

**Comment by zearp** [comment]
Thank you for the kind words. Not sure what you mean with Big Sur update, currently Big Sur is fully supported, I just don't recommend using it (yet). But you can use the EFI to update to/or cleanly install Big Sur just fine, check [this](https://github.com/zearp/Nucintosh#big-sur) section for some more info.

I don't think it's possible to get working DRM using just iGPU, other than basic iTunes trailers. I don't have Netflix but I do have Amazon Prime and others and none of it works in Safari or any other browser I've tried. I'm surprised Netflix allows 720p.

The only way to get working DRM on the NUC is to use a dGPU over Thunderbolt, which can get quite expensive if you need a card and a case. Currently DRM is completely broken on Big Sur and Safari 14 due to Lilu user space patching not working properly yet. It may work if you have a supported dGPU but unlikely on Big Sur until Lilu is fixed. Check out these links:

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md

https://dortania.github.io/OpenCore-Post-Install/universal/drm.html

The Akasa is great case, I'm really surprised by its cooling capacity. Having a completely silent machine is much nicer than expected.

Sorry for the bad news regarding DRM, I'll close this issue because there's nothing I can do.

(Apple has their own iGPU VBIOS which does the DRM which is why we can't see just iGPU for DRM. There is a theoretical option of flashing the VBIOS of a Mac mini 2018 which has the exact same iGPU. But I have no idea if this would work, but it is possible to modify the BIOS and replace the VBIOS inside of it and of course you'd need a VBIOS from the Mac mini too.)

**Comment by zearp** [comment]
Thank you for the kind words. Not sure what you mean with Big Sur update, currently Big Sur is fully supported, I just don't recommend using it (yet). But you can use the EFI to update to/or cleanly install Big Sur just fine, check [this](https://github.com/zearp/Nucintosh#big-sur) section for some more info.

I don't think it's possible to get working DRM using just iGPU, other than basic iTunes trailers. I don't have Netflix but I do have Amazon Prime and others and none of it works in Safari or any other browser I've tried. I'm surprised Netflix allows 720p.

The only way to get working DRM on the NUC is to use a dGPU over Thunderbolt, which can get quite expensive if you need a card and a case. Currently DRM is completely broken on Big Sur and Safari 14 due to Lilu user space patching not working properly yet. It may work if you have a supported dGPU but unlikely on Big Sur until Lilu is fixed. Check out these links:

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md

https://dortania.github.io/OpenCore-Post-Install/universal/drm.html

The Akasa is great case, I'm really surprised by its cooling capacity. Having a completely silent machine is much nicer than expected.

Sorry for the bad news regarding DRM, I'll close this issue because there's nothing I can do.

(Apple has their own iGPU VBIOS which does the DRM and which is why we can't use just iGPU for DRM. There is a theoretical option of flashing the VBIOS of a Mac mini 2018 which has the exact same iGPU. But I have no idea if this would work, but it is possible to modify the BIOS and replace the VBIOS inside of it and of course you'd need a VBIOS from the Mac mini too.)

**Comment by SeaDaddytheRed** [comment]
Thank you for the lengthy reply!  I read through your links and see there is no real hope yet for DRM certified Netflix on Safari.  It's okay though.  I have other devices to watch streaming on.

I think I will go ahead and update to Big Sur.  If the Error 66 is only at boot and doesn't affect daily operations then I think I am good.  I don't use Time Machine either.  (Is that what the snapshots are for?)

**Comment by zearp** [comment]
The error 66 happens when you try to modify certain parts of the filesystem in Big Sur. Apple has implement a cryptographic seal of the system volume. The snapshots used there (apfs) have no bearing on (local) Time Machine snapshots. You won't have any issues with Big Sur unless you want to modify the file system. Which is still possible but not in a way that's easy and they made it even harder in the latest builds.

I'm sure in time there will be better solutions. Until that time they only way to modify the file system now is to mess with filesystem (apfs) snapshots. Which isn't too difficult but it's also not difficult for it to go wrong and leave you with a machine that can't boot, or only boots into recovery. I would stay away from it unless really necessary and always make a bootable backup of your working system before doing so.

The same would apply to updating/upgrading your system. Creating a bootable backup can be done for free and it only costs you a usb stick or old external disk. With a bootable backup of your installed macOS + backup of your EFI on it you can always get back into a working macOS. And it's good to have a backup too. I made a small guide on how to make such a clone [here](https://github.com/zearp/OptiHack/blob/master/text/CLONE_IT.md).

It's unfortunate Apple uses their own VBIOS for DRM stuff. I might experiment with flashing another VBIOS but I can't find a reliable source for the Apple version of the Intel Iris VBIOS I need for the NUC. I'm not too worried about bricking the NUC. Intel has a good BIOS recovery methods and I also have a BIOS programmer. Just don't want to waste my time on a VBIOS found on some forum that might not be a clean or complete dump. But it's something I been wanting to experiment with at some point. Like you I have other means to play the DRM content (mainly Airplay and Chromecast). It might even be possible to run some DNLA/Airplay/Chromecast server on macOS and then cast the DRM content to your NUC or maybe something using Kodi.

I'll update the repo whenever I find new solutions or problems but for now there aren't any real major issues other than DRM and Big Sur locking down the filesystem. I've been using several NUCs since I started this repo and they've been very stable and reliable. I hope Apple will add an option to disable it temporarily with ```csrutil```. Till then the only thing you might need full access for is to replace Apple's wireless driver for some Apple airport cards and to hide the card icon that appears when using the onboard Intel bluetooth and wireless. 

You're welcome, lengthy replies are pretty normal for me on GitHub. I like to document my hackintosh stuff (mostly for myself). There are so many facets it's easy to lose track. I often forget many things and then look at my Github repo's to catch up lol.

PS: If you see any errors relating to the filesystem on boot let me know. I ran into it a couple of times with the beta's but haven't since the final release. Every now and then I do a clean install with the latest Big Sur build to check if everything works as it should. I will stay with Catalina as daily driver for the time being. I prefer to wait until at least a 3rd or 4th minor release; Big Sur 11.3 or 11.4. But thats just my personal preference.

**Comment by SeaDaddytheRed** [comment]
I finished updating to Big Sur.  It took a while on some of the reboots but I just left it and it's now updated and looking good.  I of course have a bootable backup of my Catalina install made with SuperDuper and a backup of my EFI too.

The VBIOS dumping sounds interesting.  Good luck finding a good source!

I don't know if I can recognize errors on boot.  The text scrolling on my screen is pretty fast and I wouldn't know what to look for.  Is there a place I can see errors after logging in?

I do have one issue that carried over from Catalina.   I still have to unplug and replug my HDMI after a long sleep of the system.  If I leave it in sleep overnight and wake it in the morning my monitor shows a No Signal message and goes back into low power mode.  The NUC is awake, keyboard lit up, and the power light is on so the system is awake.  But to get the HDMI back I have to unplug and replug it.  Should I maybe start a new issue thread with this problem?

**Comment by zearp** [comment]
That would be the correct option yes, some screens might need it. I haven't needed it for any of my screens. Let me know if it helped. I'll add the ```force-online``` option to the config if it solves it.

**Comment by SeaDaddytheRed** [comment]
So far it seems to solve the problem.  I have only tested it with it in sleep for about 20 minutes but the monitor is now turning on no problem.  I imagine even over night it would still work.  I have an LG 27GL850.

**Comment by zearp** [comment]
Thank you for reporting back. I've added the option to the frame buffer patch in the config. I like to keep the boot flags to a minimum but using the boot flag will do the same.

https://github.com/zearp/Nucintosh/commit/061ce18597064feef2bc2aacbb62b9831b747b28
