### ISSUE TITLE
Drift screensaver stutters

### ISSUE THREAD

**Issue by superchief** [zearp/Nucintosh#28]
Hi, I'm very pleased with your work and appreciate all your effort. For the most part everything works great. The only thing I see is that if you use the Drift screensaver, it stutters. It's not a big deal, but I wanted to point it out.

**Comment by zearp** [comment]
What resolution do you use? On mine Drift is a bit jumpy every so often but no stuttering on my 1080p screen.

My guess on the cause is that it seems Apple didn't optimise it for the Iris graphics very well. Which is present in our NUC and Macs too, some even have the exact same model. Because I've seen quite  number of complaints on Apple support and other Apple forums about Drift. Including people with very recent models. The thing they seem to have in common is that they all have an Iris based graphics chip.

Luckily it does only seem to affect this screensaver as graphic performance is fine elsewhere.

You could try to max out the VRAM to take up 2gb instead of 1.5gb. Not sure if that would help though. To max out the VRAM add an entry called ```framebuffer-unifiedmem``` with a data value of ```00000080``` in the frame buffer section of the config and reboot.

![Screenshot 2021-02-03 at 22 24 59](https://user-images.githubusercontent.com/63272687/106811793-24383b00-666f-11eb-9b66-a8356f5d6af3.png)

**Comment by superchief** [comment]
I just got around to try your suggestion. It didn't work, but again I want to emphasize that this is not a big deal and I really appreciate you posting your boot-loader and guide.

FYI- It's on a Dell Model S3220DGF 2560x1440 144 Hz monitor
So not 1080p like you have.

**Comment by zearp** [comment]
Bummer increasing VRAM didn't help. A few months ago when starting this repo I ran benchmarks such a Geekbench and Cinebench and the graphical performance was how it's supposed to be. It performed on par with the 2018 Mac mini and MBP. Seems the issue lies solely in the screensaver itself.

To me this is confirmed by reports of people with 2019/2020 Mac models who experience the exact same issue with Drift. Maybe messing about with the base clocks can help but I doubt that. The frequency wil scale up when it's needed anyways, so running at a higher base clock will just produce more heat and use more energy.

I don't have any modern Macs to test it on but I can confirm my old MBP with HD4000 also has the short hiccups with Drift, the same goes for my HD4600 Dell OptiPlex hacks. None of them can run this screensaver smoothly. I don't have other systems to test it on. It would be interesting to see how it performs with an e-gpu but my money tree is empty. They're not cheap and I also don't know anyone with one I could borrow.

If you're up to experiment there are some WhateverGreen options that could help performance. Like enabling rps control by using ```igfxrpsc=1``` boot flag or adding ```rps-control``` to the frame buffer config. I haven't enabled that or others as it can break things or cause instability. I don't have the time to test those the way I want to. But who knows, maybe it can be tweaked to perform better by playing around with WhateverGreen options.

I've closed the issue since there's really nothing I can do about it. We have a chip thats natively supported by macOS and we get the same performance as real Macs with it, which also seem unable to smoothly run this screensaver. Maybe Apple will optimise it or maybe they won't. I will of course implement and update the repo if there are tweaks that work and don't cause any issues elsewhere.

My best suggestion is to use a different screensaver. Flurry performs great and gives you some retro bonus points.
