### ISSUE TITLE
4k 60Hz with Samsung monitor pink screen / garbled etc

### ISSUE THREAD

**Issue by bernek9000** [zearp/Nucintosh#29]
I have severe problems using 4K at 60Hz with Intel Nuc 8th gen its an i3. The problem is that screen starts to flicker and becomes garbled eventually. At 50Hz everything is fine. The screen works fine on Windows 10 at 60Hz (monitor is brand new). Is there a way to switch the colors to be RGB in macOS ? Can you help me try that ?

Thanks.

**Comment by zearp** [comment]
This isn’t the place to get support with setting up devices. I’m just one person and if I start helping everybody setting up their machines I’ll have a new job. Please try hackintosh forums and Reddit. Plus, I don’t have a 4K screen so there’s nothing for me to test or try out. I’d just be guessing.

**Comment by bernek9000** [comment]
I appreciate it !

**Comment by zearp** [comment]
I forgot to ask if you use Big Sur or Catalina.

Things relating to 4k seems pretty broken/buggy in Big Sur. This is due to many things including Lilu user space patching not working properly in Big Sur yet. If you have only tried Big Sur also try Catalina. It may just work fine in there.

I'm hoping to get a 4k screen at some point this year, till then it will be impossible for me to trouble shoot issues with it. The best I can do is guess which most likely will be unhelpful and a waste of time lol.

**Comment by bernek9000** [comment]
I've tried both and the problem is the same. I use switchresx to change to 50hz and it works. Still annoying because the monitor works fine at 60hz in other OS. Also tried cables that are certified. I dont know how to change the EDID of the display or to force macOS to use RGB mode instead of other color formats. I think the problem comes from this ... I've googled it for a few days but couldn't find a way to do it except:
https://www.mathewinkson.com/2013/03/force-rgb-mode-in-mac-os-x-to-fix-the-picture-quality-of-an-external-monitor#comment-15886
I don't fully comprehend how to this.

**Comment by zearp** [comment]
Sounds annoying indeed. I don't know why macOS is so fussy with these kind of things. I use [this](https://gist.github.com/ejdyksen/8302862) to fix EDID on one of my screens. Don't know if this works in Big Sur since the file system there is locked down but it works on Catalina. Just follow the instructions and hopefully it resolves some of your issues. I see a lot of people struggle with 4k, especially with Big Sur.

**Comment by bernek9000** [comment]
I want to thank you for the help ! I will look further and dont give up maybe I will find a way :) Thanks !

**Comment by rvmn** [comment]
Hi, I had a similar problem with an LG 4K monitor which gave me magenta/pink image. It happened after upgradeing Big Sur and I solved it by changeing the Device Properties for the GPU. In the config.plist (opened in Text editor) search for framebuffer and select and replace the dictionary key for with th e following blob:

**Comment by zearp** [comment]
@rvmn So do you know which setting fixes things? Also the frame buffer you pasted is not properly setup. So my guess is that either adding ```enable-hdmi20``` fixes it or the removal of some of the other settings. it's not really helpful to just paste in a new frame buffer without finding out that were the actual causes and if you do at least make sure it's properly setup. You made a lot of changes, so many I don't think yours was based on the one I made.

The lspcon entries are sure wrong cuz only one port has lspcon on the NUC. Also you've removed loading Apple's GUC firmware. Why? So many changes in the framebuffer and all I can ask is why? Please explain everything you changed form the original and why. Cuz right now it looks like you found some semi compatible framebuffer from another build and use it here. Thats not the right way to do things.

I wouldn't recommend anyone to use what you pasted or edit the config with a text editor and just pasting things in cuz it can easily break a plist formatted file. Edit the config with ProperTree and test changes one by one so you know exactly what causes/fixes the issue. That will help others, simply yelling people to replace my framebuffer with something thats incomplete is not the way to go. Your framebuffer will result in lower performance for sure since it doesn't use Apple's GUC firmware. Also your framebufffer is spoofing a device id, why? Our chip is natively supported and doesn't need device id spoofing.

I'd much prefer people helping to make things better the right way, by finding out methodically and properly why things happen and fix them the way it should. If you really wanna help make things better than restore the normal framebuffer and start by disabling all the options not enabled in the one you pasted, simply set them to all zero's. Then by trial and error you can find out exactly which settings causes/fixes the pink hue on some screens. Telling people to add your incomplete framebuffer is not good.

Here's the 2 side by side:

![Screenshot 2021-06-02 at 14 36 02](https://user-images.githubusercontent.com/63272687/120481256-37a2ab00-c3b0-11eb-82e1-18d571ab2d0b.png)
![Screenshot 2021-06-02 at 14 36 12](https://user-images.githubusercontent.com/63272687/120481276-3bcec880-c3b0-11eb-9cb3-6f81abfd3499.png)

I won't go over everything but for sure the lspcon is wrong cuz you have to define which ports have it, on the NUC that's only the hdmi port. If you really wanna help out; restore the original and do some testing to find the cause/fix by enabling/disabling options and see which ones do the job. That would help everybody who uses this repo, telling people to copy paste an incomplete framebuffer is not helping anyone and could even cause other issues, like for those that need lspcon to work properly. 

Please don't post stuff you haven't properly tested and could mess up people's config. It's not hard to do proper testing just time consuming. I have several screens I use here and none gave me a pink hue so I can't do any testing on this myself. It appears some screens have it while others don't with the same config. Figuring out what setting caused it is easy but needs to be done by someone who experiences this and has the time/skills to do proper testing.

**Comment by zearp** [comment]
@rvmn So do you know which setting fixes things? Also the frame buffer you pasted is not properly setup. So my guess is that either adding ```enable-hdmi20``` fixes it or the removal of some of the other settings. It's not really helpful to just paste in a new frame buffer without finding out the causes and if you do at least make sure it's properly setup. You made a lot of changes, so many I don't think yours was based on the one I made and was taken from some other place.

The lspcon entries are wrong cuz only one port has lspcon on the NUC and it needs to setup, refer to the [WhateverGreen FAQ on lspcon](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#lspcon-driver-support-to-enable-displayport-to-hdmi-20-output-on-igpu). Also you've removed loading Apple's GUC firmware. Why? So many changes in the framebuffer and all I can ask is why? Please explain everything you changed from the original and why. Cuz right now it looks like you found some semi compatible framebuffer from another build and use it here. Thats not the right way to do things.

I wouldn't recommend anyone to use what you pasted or edit the config with a text editor and just pasting things in cuz it can easily break a plist formatted file. Edit the config with ProperTree and test changes one by one so you know exactly what causes/fixes the issue. That will help others, simply telling people to replace my framebuffer with something thats incomplete is not the way to go. Your framebuffer will result in lower performance for sure since it doesn't use Apple's GUC firmware. Also your framebufffer is spoofing a device id, why? Our chip is natively supported and doesn't need device id spoofing.

I'd much prefer people helping to make things better the right way, by finding out methodically and properly why things happen and fix them the way it should. If you really wanna help make things better than restore the normal framebuffer and start by disabling all the options not enabled in the one you pasted, simply set them to all zero's. Then by trial and error you can find out exactly which settings causes/fixes the pink hue on some screens.

Here's the 2 side by side:

![Screenshot 2021-06-02 at 14 36 02](https://user-images.githubusercontent.com/63272687/120484363-49398200-c3b3-11eb-9d57-c3aca9e0bb65.png)
![Screenshot 2021-06-02 at 14 36 12](https://user-images.githubusercontent.com/63272687/120484376-4c347280-c3b3-11eb-8b8f-be271426c118.png)

I won't go over everything but for sure the lspcon is wrong cuz you have to define which ports have it, on the NUC that's only the hdmi port. If you really wanna help out; restore the original and do some testing to find the cause/fix by enabling/disabling options and see which ones do the job. That would help everybody who uses this repo, telling people to copy paste an incomplete framebuffer is not helping anyone and could even cause other issues, like for those that need lspcon to work properly. 

Please don't post stuff you haven't properly tested and could mess up people's config. It's not hard to do proper testing just time consuming. I have several screens I use here and none gave me a pink hue so I can't do any testing on this myself. It appears some screens have it while others don't with the same config. Figuring out what setting cause/fix it is easy.

**Comment by zearp** [comment]
@bernek9000 If you still have issues and if you're up for some testing I can make some different configs for you to try. Then you just tell me which ones work and which ones don't. 4k should work both with usb-c/dp and hdmi. If you use hdmi and don't get 4k @ 60hz then maybe something is wrong with my connectors map. The hdmi port needs lspcon to be enabled in order to do 4k @ 60hz. If you want to test first make a backup of your current EFI just in case and then update to the latest version of the repo. Just download the current [master zip](https://github.com/zearp/Nucintosh/archive/refs/heads/master.zip) and extract the EFI folder from it.

I have tested 4k using hdmi and it worked for me using a real 4k screen and also a hdmi headless dongle that goes up to 4k. So I think my connectors are configured properly. But some screens may need or not need certain options enabled to work properly. The latter is hardest to deal with but most fixes don't break other things. Like the ```force-online``` options is not needed for most of us but some screens simply don't wake up after sleep without it. There is however a small chance one of those options breaks something on other screens. It is impossible for me to test all the combinations possible. The best I can do is mek a config that works as best as it can on most screens.

Testing would just involve you swapping out config files and booting into them and see what it does. There's not much else I can do other than buying the exact same screen as you have and repeat the tests. But unfortunately I don't have the funds fo that haha. We just gotta find out which settings cause/fix the hue and other issues you experience on that screen. And then see if the fixes can be applied in a way that doesn't break anything elsewhere and fix it for you (and others) who run into these.

**Comment by zearp** [comment]
@bernek9000 If you still have issues and if you're up for some testing I can make some different configs for you to try. Then you just tell me which ones work and which ones don't. 4k should work both with usb-c/dp and hdmi. If you use hdmi and don't get 4k @ 60hz then maybe something is wrong with my connectors map. The hdmi port needs lspcon to be enabled in order to do 4k @ 60hz. If you want to test first make a backup of your current EFI just in case and then update to the latest version of the repo. Just download the current [master zip](https://github.com/zearp/Nucintosh/archive/refs/heads/master.zip) and extract the EFI folder from it.

I have tested 4k using hdmi and it worked for me using a real 4k screen and also a hdmi headless dongle that goes up to 4k. So I think my connectors are configured properly. But some screens may need or not need certain options enabled to work properly. The latter is hardest to deal with but most fixes don't break other things. Like the ```force-online``` options is not needed for most of us but some screens simply don't wake up after sleep without it. There is however a small chance one of those options breaks something on other screens. It is impossible for me to test all the combinations possible. The best I can do is make a config that works as best as it can on most screens.

Testing would just involve you swapping out config files and booting into them and see what it does. There's not much else I can do other than buying the exact same screen as you have and repeat the tests. But unfortunately I don't have the funds for that haha. We just gotta find out which settings cause/fix the hue and other issues you experience on that screen. And then see if the fixes can be applied in a way that doesn't break anything elsewhere and fix it for you (and others) who run into these. Let me know if you're up for it.

**Comment by rvmn** [comment]
You are totally right, thanks for checking it out! The changes seemed to fix the problem but I found the actual really working solution now and its a lot simpler (and not requiring a broken graphics setting  thanks for pointing that out!): it's a cold boot. If you just shut off instead of restarting (i did usually, usually from windows or linux) and start from a 'cold' boot I never have the issue. Do you think it might be related to the NVRAM or some temporary memory? in that case maybe a future opencore release might solve it then. Thanks for helping, I think this is solved.

**Comment by zearp** [comment]
Ohh that is a very interesting find! I don't know enough about how the monitor talks to the system but maybe something differs from when it happens vs a cold boot when its always good. It could be that one of the options that wasn't present in framebuffer causes the issue only in certain scenarios. If you can narrow down which option it is you can then figure out what it does.

I've not had the hue issue but it did have issues where some screens don't wake up after sleep, which is fixed with the force-online option, that might also interfere maybe. I also load the Apple GuC firmware which isn't done by default in WhateverGreen but it does improve performance. Another thing to try is injecting EDID and maybe a different/custom display profile.

I don't know enough about it and its a bandaid. the cause must be somewhere in WhateverGreen and the options in combination with your screen or macOS. There are a lot of variables but at least you have a reproducible method in where it never happens. You could try setting up debug version of WEG/Lilu/OpenCore and enable logging and see if you can spot anything when it happens and when its normal. I would also make an IOreg dump for both cases and compare them. If they differ that may also lead to more clues. If you got the time and patience it can be quite enjoyable to hunt these things down but if you just need things to work they can become frustrating lol. Luckily you can do a cold boot when you don't want to deal with it!

Thanks for sharing.

**Comment by tristan-k** [comment]
> You are totally right, thanks for checking it out! The changes seemed to fix the problem but I found the actual really working solution now and its a lot simpler (and not requiring a broken graphics setting thanks for pointing that out!): it's a cold boot. If you just shut off instead of restarting (i did usually, usually from windows or linux) and start from a 'cold' boot I never have the issue. Do you think it might be related to the NVRAM or some temporary memory? in that case maybe a future opencore release might solve it then. Thanks for helping, I think this is solved.

I can confirm that a cold boot also fixed the issue for me on two different 4k displays. Thanks!
