### ISSUE TITLE
Thunderbolt  3  USB no response

### ISSUE THREAD

**Issue by TokiharaSay** [zearp/Nucintosh#35]
After flashing the Thunderbolt firmware, the USB of the Thunderbolt port cannot be hot-plugged or the boot device is not inserted. There is no Thunderbolt USB controller. Is there such a situation?

![](https://cdn.jsdelivr.net/gh/TokiharaSay/Pic/NUC8/iShot2021-03-23%2009.38.04.png)
![](https://cdn.jsdelivr.net/gh/TokiharaSay/Pic/NUC8/iShot2021-03-23%2009.39.40.png)

**Comment by zearp** [comment]
Hmm, it should work but I'll have to recheck on my test NUC with its firmware patched and using the current EFI. Mind you the Thunderbolt patching is far from perfect since it's pretty much using the same method as for another NUC model that shares the same chipset and while that part works perfectly the ACPI patches and config might not be fully compatible or may need some fixes. Which is above my pay grade unfortunately, I'd need to study [the ACPI spec](https://uefi.org/sites/default/files/resources/ACPI_6_3_final_Jan30.pdf). Which isn't on my wish list at the moment haha.

I'll do some testing hopefully tomorrow and see how it goes. Can I assume you had no problems with this before patching the firmware and both thunderbolt and usb worked fine? The only reason to patch is if you really need Thunderbolt hotplugging, specially since it breaks sleep to patch and also hampers Thunderbolt in Windows. I've been using unpatched on my main NUC without any issues using Thunderbolt or usb devices.

**Comment by TokiharaSay** [comment]
I don’t use win, and I don’t care about sleep problems. The main reason is that I use Thunderbolt hard disk box, but when I use Thunderbolt port to plug in the USB device, there is no response, and even the Thunderbolt USB controller does not plug into the device during cold start exist
![](https://cdn.jsdelivr.net/gh/TokiharaSay/Pic/NUC8/iShot2021-03-23%2011.21.27.png)

**Comment by zearp** [comment]
Does it happen only after using a Thunderbolt device or is the port also not working for you after patching?

On my test system I always use a usb-c hub to connect to hdmi and usb for keyboard and mouse and both the video output as the usb ports on the hub work before and after patching. 

I don’t have any Thunderbolt 3 devices to test with. I have some Thunderbolt 2 but no conversion cable to connect them.

**Comment by TokiharaSay** [comment]
The USB controller becomes unavailable only after applying the patch，But Thunderbolt 3  is normal。

**Comment by zearp** [comment]
I've had some time to try on my test NUC and if I boot up with a usb-c hub connected things work fine and the Thunderbolt usb controllerships up.

If I boot up with the usb-c hub disconnected the Thunderbolt usb controller doesn't show up, even after connecting the hub again. 

Reverting the patch and using the post-firmware-patch ACPI patch makes usb-c hotplug work again but of course no Thunderbolt hotplug then. 

So it appears that patching the firmware to fix Thunderbolt hot plugging break some other stuff. As test try adding the attached ACPI patch to your config and see if that does anything.

[SSDT-TYPC-NUC8-BC.aml.zip](https://github.com/zearp/Nucintosh/files/6193655/SSDT-TYPC-NUC8-BC.aml.zip)

Let me know your results and also what happens if you just add the above ACPI patch to the current setup.

**Comment by zearp** [comment]
I've had some time to try on my test NUC and if I boot up with a usb-c hub connected things work fine and the Thunderbolt usb controllerships up.

If I boot up with the usb-c hub disconnected the Thunderbolt usb controller doesn't show up, even after connecting the hub again. 

Reverting the patch and using the post-firmware-patch ACPI patch makes usb-c hotplug work again but of course no Thunderbolt hotplug then. 

So it appears that patching the firmware to fix Thunderbolt hot plugging break some other stuff. As test try adding the attached ACPI patch to your config and see if that does anything.

[SSDT-TYPC-NUC8-BC.aml.zip](https://github.com/zearp/Nucintosh/files/6193685/SSDT-TYPC-NUC8-BC.aml.zip)

**Comment by zearp** [comment]
I've had some time to try on my test NUC and if I boot up with a usb-c hub connected things work fine and the Thunderbolt usb controllerships up.

If I boot up with the usb-c hub disconnected the Thunderbolt usb controller doesn't show up, even after connecting the hub again. 

Reverting the patch and using the post-firmware-patch ACPI patch makes things work again but of course no Thunderbolt hotplug. 

So it appears that patching the firmware to fix Thunderbolt hot plugging breaks some usb Thunderbolt related stuff. As a test try adding the attached ACPI patch to your config and see if that does anything.

[SSDT-TYPC-NUC8-BC.aml.zip](https://github.com/zearp/Nucintosh/files/6193696/SSDT-TYPC-NUC8-BC.aml.zip)

**Comment by zearp** [comment]
I've had some time to try on my test NUC and if I boot up with a usb-c hub connected things work fine and the Thunderbolt usb controller shows up.

If I boot up with the usb-c hub disconnected the Thunderbolt usb controller doesn't show up, even after connecting the hub again.

Reverting the patch and using the post-firmware-patch ACPI patch makes things work again but of course no Thunderbolt hotplug.

So it appears that patching the firmware to fix Thunderbolt hot plugging breaks some usb Thunderbolt related stuff. As a test try adding the attached ACPI patch to your config and see if that does anything.

[SSDT-TYPC-NUC8-BC.aml.zip](https://github.com/zearp/Nucintosh/files/6193720/SSDT-TYPC-NUC8-BC.aml.zip)

**Comment by TokiharaSay** [comment]
Yes, using this SSDT-TYPC-NUC8-BC, the USB is normal, but there is no Thunder, then I restored the firmware, and now using these two SSDTs, Thunder’s usb controller is not available
Use _E40 TO XE40
[TB3.zip](https://github.com/zearp/Nucintosh/files/6195348/TB3.zip)

**Comment by zearp** [comment]
Ah ok, thanks for trying. Seeing as I have no Thunderbolt 3 devices there's nothing else I can do cuz I can't test anything myself. I guess you'll have to choose, don't patch Thunderbolt firmware and have everything working except for Thunderbolt Hotplug, or patch the firmware and use the Thunderbolt port only for Thunderbolt devices since usb breaks. Nothing else I can do. Someone with deep ACPI/Thunderbolt knowledge needs to check and fix things here. It is above my pay grade.

All NUC8 Thunderbolt patches use the work of Osy. But his patches are written for a different NUC that shares the exact same Thunderbolt chip. So while the patch might be appleid perfectly the ACPI patches and config my need fixing before everything works properly. I have opened [an issue](https://github.com/osy/ThunderboltPatcher/issues/8) on his repo about the panic when waking up from sleep after patching but I haven't heard anything back on that. Can't blame him for not wanting to support or help out with a machine he doesn't own. 

You can remove/undo all patches and try for yourself from scratch using these resources but you'll need to be sufficient in ACPI which I'm not.

https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix

We'll need someone with advanced knowledge regarding ACPI and Hackintosh to make Thunderbolt work like native. Till then the best configuration would be to not patch it as most people won't be hot plugging Thunderbolt devices all the time and do want working sleep. 

For you since you need the hot plugging you have to make do with using the Thunderbolt port for Thunderbolt and maybe you can help find a solution for this and help fix this. Every single repo for the Coffee Lake NUC8 that uses these patches will have the same issues since we all use the same methods, ACPI patches and firmware modification.

I haven't seen anyone manage to get full working sleep with the patched firmware but also didn't read about a usb controller disappearing. I think they simply didn't notice and (like me) were focussed on trying to fix sleep. You can try other EFI's found on Github and other sites and if any of those makes the usb controller come back when running the patched firmware let me know so I can see how it works and implement it here.

**Comment by TokiharaSay** [comment]
Okay, thank you very much for your help, I will tell you if there is a way

**Comment by Lorys89** [comment]
> Okay, thank you very much for your help, I will tell you if there is a way

Hi toki, h9 a nuc8i3beh with thunderbolt bricked fw, I need the original fw to flash it with spi, do you have it? If yes you can send it?
