### ISSUE TITLE
DualScreen not Working At Startup

### ISSUE THREAD

**Issue by AngealGeek** [zearp/Nucintosh#36]
Hi!
Thanks for this amazing Nucintosh.
I just saw than my hackintosh can't boot with dual screen plugged (HDMI+thunderbolt) ==+> crash on Apple Logo

But if i plugged the second cable only after the loading screen everything works well.

**Comment by zearp** [comment]
Is the screen connected over Thunderbolt or usb-c? I’ve only tested with usb-c to hdmi + hdmi on the back and that worked at the time.

**Comment by AngealGeek** [comment]
Yes i connect on the Back, tested with two differents screen but i use  usb C to VGA + HDMI instead of USB C to HDMI.

Maybe this is it, i will probably buy an USB C to HDMI and try again with a 3rd screen

**Comment by zearp** [comment]
I'm surprised VGA works on manual plug-in because VGA isn't support by macOS anymore. Which would explain why it's not working (properly). If I understand correctly you're using several dongles to get video output from the usb-c port. Its best to use straight dongles and not a chain of conversion as it will cause issues.

Dongles and conversion is known to cause issues too. One dongle might work and another might cause problems. I've had one person using my other EFI who had weird display issues that were solved by using a different dp -> hdmi cable. Not all converters convert the same I guess.

I'm really surprised you got any output at all over VGA. Normally to get it working in modern macOS you'll need a converter that does the analog to digital conversion for you and also use a SMBIOS from a Mac that still had a VGA port. 

As for the Thunderbolt question, it was for me to know what type of connection you used to connect your screen. The usb-c port on the back supports both usb and Thunderbolt. So you can either use a usb-c to hdmi/dp dongle/hub or a Thunderbolt Display/hub. I picked up some small usb-c hubs from Amazon for around $10 a piece a while ago. They have 3 usb 3.0 ports and a hdmi output. Good value and working great in macOS:

![61edmDCAU6L](https://user-images.githubusercontent.com/63272687/112148422-28e48e80-8bde-11eb-9e29-8a8df8607c52.jpg)

They're sold as different brands in many places. A simple small metal box that provides a few extras. I use mine for my wireless keyboard/mouse usb dongle and hdmi so there's just 2 cables to swap when I try another NUC. If only Intel allowed us to power the NUC over usb-c too. A one cable solution would be nice.

**Comment by AngealGeek** [comment]
Thanks for your answer and your time! i will buy something like that and i will keep you informed.

Oh Sorry i wasnt clear, i use a little converter, this one:
https://www.amazon.com/Adapter-Thunderbolt-Converter-Compatible-MacBook/dp/B076X2XS9R/ref=sr_1_3?dchild=1&keywords=benfei+usb+c+vga+adapter&qid=1616518531&sr=8-3

But i did not change anything about the SMBIOS.

Here is the NUC 10 with your Vanilla EFI, i plugged my converter when already running and everything smooth well
[https://drive.google.com/file/d/1c4tNbHxihjTKgNLVBgdZuEPeEFtDV89Y/view?usp=sharing](url)


Boot with everything plugged: 
[https://drive.google.com/file/d/1c21KlpEDaA9aYIWpJ7ke-usw1Vc5nE6T/view?usp=sharing](url)

**Comment by zearp** [comment]
Ah, I see the converter has a pcb inside dong the analog to digital translations. Didn't know they made these haha. I guess if for the system this appears as a digital output it should just work no matter whats it converting, pretty neat!

Mind you this repo is for NUC8 so for NUC10 you need to make changes to the frame buffer and maybe other parts too. But I'm pretty sure the NUC10 has a UHD based and NUC8 is Iris based. Your problem may go away if you change the frame buffer settings to match your chip.

Change *platform-id* from ```0400A53E``` to ```07009B3E``` and add a new entry in the same section called *device-id* with a data ```9B3E0000```. It may not change anything but those are the correct settings for the UHD 620 in the NUC10.

Other changes may also be needed, check out the laptop (NUC uses laptop stuff) Comet Lake section of the guide [here](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html). Many things are the same but it's worth to to check your config against the guide cuz this repo is only tested on/made for NUC8 and maybe things do not work properly or could be better. If anything differs just try and see how it goes. You can always revert the changes if there's no improvement.

**Comment by zearp** [comment]
Ah, I see the converter has a pcb inside doing the analog to digital translations. Didn't know they made these haha. I guess if for the system this appears as a digital output it should just work no matter what its converting, pretty neat!

Mind you this repo is for NUC8 so for NUC10 you need to make changes to the frame buffer and maybe other parts too. But I'm pretty sure the NUC10 has a UHD based and NUC8 is Iris based. Your problem may go away if you change the frame buffer settings to match your chip.

Change *platform-id* from ```0400A53E``` to ```07009B3E``` and add a new entry in the same section called *device-id* with a data ```9B3E0000```. It may not change anything but those are the correct settings for the UHD 620 in the NUC10.

Other changes may also be needed, check out the laptop (NUC uses laptop stuff) Comet Lake section of the guide [here](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html). Many things are the same but it's worth to to check your config against the guide cuz this repo is only tested on/made for NUC8 and maybe things do not work properly or could be better. If anything differs just try and see how it goes. You can always revert the changes if there's no improvement.
