### ISSUE TITLE
There's something wrong with the releases  version of SuperIO.kext. I can't read the fan speed.

### ISSUE THREAD

**Issue by frozenzero123** [zearp/Nucintosh#38]
The releases version of superIO seems to have a problem. the fan speed of nuc8 cannot be displayed (the version you updated the other day can be)

**Comment by zearp** [comment]
Can confirm this one, I have no idea whats happening but when I compile from source everything looks good just no fan readings. When using a pre-compiled snapshot ratings fan speeds works. I build everything from source, somewhere something is breaking reading out fan speeds. I'll investigate and till that time use a snapshot so reading fans works again.

**Comment by zearp** [comment]
Should be sorted now: https://github.com/zearp/Nucintosh/commit/aada1b1b77f5a5b93302f81177f0250559e9cfa7

You can use attached kexts and replace the ones in your EFI to get fan speeds back.

[SMC.zip](https://github.com/zearp/Nucintosh/files/6277954/SMC.zip)

I have no clue why my own compiled version doesn't work since it compiles without issues and works fine... apart from fan readings haha. I'll dig into this at a later time. Thank you for spotting and reporting it. I wouldn't have noticed myself because my main NUC is cooled passively.
