### ISSUE TITLE
Manual question BCM94360CS2

### ISSUE THREAD

**Issue by murmeltier08** [zearp/Nucintosh#39]
> The two internal usb ports are already mapped in the USBPorts.kext, if you made your own map you'll need to make a new map if you use the internal usb headers
> When using a 1st or 3rd party combo card you need to disable both bluetooth and wifi in the BIOS and also remove any Intel related bluetooth and wifi kexts
> You will also need to remove the config block for HS10 from Info.plist inside USBPorts.kext, without this step bluetooth won't work after sleep. On 1st party cards it gets "stuck" in HID-proxy mode; bluetooth mouse and keyboard may still work but not optimally and laggy.

Can you please tell the reason why I have to delete this Block? I use your USBPorts.kext and install now my BCM94360CS2 at HS05. I have not to delete any block. If I delete the block my BCM94360CS2 not working. Can you explain it to me please.

**Comment by zearp** [comment]
Can't reduce this. 

I use the exact same card as you have in 2 NUCs and have no issues at all and both have HS10 removed.

Reason is explained in the text. If you don't remove HS10 then bluetooth HID mode stops working properly.  It's not possible that removing HS10 breaks anything else cuz the only thing thats connected to HS10 is the Intel combo card.

You can easily test this, pair your bluetooth keyboard and mouse and leave the HD10 block in place, put the machine to sleep and wake it up. Your mouse and keyboard will now be laggy and mouse wheel might not work anymore. Bluetooth can't be turned on or off anymore as well.

Removing HS10 and doing above steps again and you will see all the problems will go away and on waking up the machine bluetooth can be turned and off and your keyboard and mouse are connected normally without lag.

Maybe you deleted too much? 

What I suspect is happening is that you didn't connect your BCM94360CS2 to an internal usb port. So in essence you were using the Intel card for bluetooth. The BCM94360CS2's bluetooth only works over usb and needs to be connected to one of the 2 tiny usb headers on the motherboard. Those are HD05 and HS06 if I'm not mistaken.

Background:

In my testing leaving HD10 when using another wifi/bt combo card will break bluetooth HID proxy and on wake the HID devices aren't handed off back to the bluetooth controller properly and remain on the usb bus (you can check this by looking at the usb devices an Apple device will shop up there) and get very laggy. And it also makes it so you can't toggle Bluetooth anymore after sleep. None of those problems exist with HS10 removed.

I spend a lot of hours to even figure out removing HS10 was needed to solve the weird keyboard and mouse lag I had with bluetooth devices after waking up from sleep when using wifi/bt combo cards.

**Comment by zearp** [comment]
Can't reproduce this.

I use the exact same card as you have in 2 NUCs and have no issues at all and both have HS10 removed.

Reason is explained in the text. If you don't remove HS10 then bluetooth HID mode stops working properly. It's not possible that removing HS10 breaks anything else cuz the only thing thats connected to HS10 is the Intel combo card.

You can easily test this, pair your bluetooth keyboard and mouse and leave the HD10 block in place, put the machine to sleep and wake it up. Your mouse and keyboard will now be laggy and mouse wheel might not work anymore. Bluetooth can't be turned on or off anymore as well.

Removing HS10 and doing above steps again and you will see all the problems will go away and on waking up the machine bluetooth can be turned and off and your keyboard and mouse are connected normally without lag.

Maybe you deleted too much?

What I suspect is happening is that you didn't connect your BCM94360CS2 to an internal usb port. So in essence you were using the Intel card for bluetooth. The BCM94360CS2's bluetooth only works over usb and needs to be connected to one of the 2 tiny usb headers on the motherboard. Those are HD05 and HS06 if I'm not mistaken.

Background:

In my testing leaving HD10 when using another wifi/bt combo card will break bluetooth HID proxy and on wake the HID devices aren't handed off back to the bluetooth controller properly and remain on the usb bus (you can check this by looking at the usb devices an Apple device will shop up there) and get very laggy. And it also makes it so you can't toggle Bluetooth anymore after sleep. None of those problems exist with HS10 removed.

I spend a lot of hours to even figure out removing HS10 was needed to solve the weird keyboard and mouse lag I had with bluetooth devices after waking up from sleep when using wifi/bt combo cards.

**Comment by zearp** [comment]
Can't reproduce this.

I use the exact same card as you have in 2 NUCs and have no issues at all and both have HS10 removed.

Reason is explained in the text. If you don't remove HS10 then bluetooth HID mode stops working properly. It's not possible that removing HS10 breaks anything else cuz the only thing thats connected to HS10 is the Intel combo card.

You can easily test this, pair your bluetooth keyboard and mouse and leave the HS10 block in place, put the machine to sleep and wake it up. Your mouse and keyboard will now be laggy and mouse wheel might not work anymore. Bluetooth can't be turned on or off anymore as well.

Removing HS10 and doing above steps again and you will see all the problems will go away and on waking up the machine bluetooth can be turned on and off and your keyboard and mouse are connected normally without lag.

Maybe you deleted too much?

What I suspect is happening is that you didn't connect your BCM94360CS2 to an internal usb port. So in essence you were using the Intel card for bluetooth. The BCM94360CS2's bluetooth only works over usb and needs to be connected to one of the 2 tiny usb headers on the motherboard. Those are HD05 and HS06 if I'm not mistaken. Also make sure you have disable Bluetooth and wifi in the bios.

Background:

In my testing leaving HD10 when using another wifi/bt combo card will break bluetooth HID proxy and on wake the HID devices aren't handed off back to the bluetooth controller properly and remain on the usb bus (you can check this by looking at the usb devices an Apple device will shop up there) and get very laggy. And it also makes it so you can't toggle Bluetooth anymore after sleep. None of those problems exist with HS10 removed.

I spend a lot of hours to even figure out removing HS10 was needed to solve the weird keyboard and mouse lag I had with bluetooth devices after waking up from sleep when using wifi/bt combo cards.

**Comment by murmeltier08** [comment]
Thank you for your Information. I connect the wlan/bluetooth like this:
![image](https://user-images.githubusercontent.com/44034211/114349379-1bc91880-9b68-11eb-81fc-1fb0ea447888.png)

But now I understand the point. I think HS10 is the Blueooth Port of the BCM94360CS2 Card. But it this is the exisiting port of the intel card.  Perhaps this will be a good additional information in the manual?

**Comment by zearp** [comment]
No, HS10 is exclusively used by the Intel combo card, we remove it because it causes issues in combination with Apple Airport cards in the m.2 slot.

HS05 and HS06 are the two internal headers (see image), removing those might not make them stop functioning but they could stop working if you go above the 15 port limit and of course removing it removes the ability to set those ports as internal which could cause sleep issues. Thats why it's important to map all the USB ports you plan to use. The internal may work now, until you connect a usb hub or something else that pushes the machine over 15 ports. And then your HS05 or HS06 thats connected to your Apple Airport card will just disappear. Or worse, act unpredictable.

I prefer to go by the book and set things up properly, removing HS10 is needed, else you will get issues as I explained above, you can even test and repeat it. If I don't remove HS10 on my NUCs where the Intel combo card is disabled and a Apple Airport card is installed then on wake up my bluetooth connected mouse and keyboard don't work properly, they appear attached to HS10 instead of header I used n the motherboard, which isn't whats supposed to happen, they're supposed to be re-attach to usb hub on the Apple Airport card.

I don't know how to explain it better, when I was testing and setting up I always had very weird lag on connected Bluetooth devices because they got stuck in proxy-hid mode. A mode that presents your paired bluetooth keyboard and mouse to the system as plain old usb device when outside of macOS such as loading up to get in bios or even if you boot up Windows. This functionality breaks if you don't remove HS10.

My process is always the same, I test everything at least twice and ran into this problem on every single NUC that uses bluetooth mouse/keyboard. Have you tried the test as I suggested? Pair a bluetooth keyboard and mouse with your NUC then reboot and make sure they work to get into the bios, that way you're sure hid-proxy is proxy. Put your macOS to sleep and wake it up after a few minutes. Doing those steps with HS10 not removed will lead to usb devices being connected to HS10 on wake and acting very laggy, on some of my mice the scroll wheel stops working too. On top of that turning bluetooth on/off no longer works until trebooted. Running the same steps with HS10 removed and you will have no such issues.

Either way, it's your computer and if it works for you then it works for you. I just can't support non-standard implementations cuz I know they can result in errors in certain use cases. You don't have to delete it if you don't want to. Just be aware that any issues regarding sleep and bluetooth stuff like hid-proxy could be caused because HS10 still existing in the map. I'd also highly recommend against removing the internal headers HS05 and HS06 from the usb map. Only remove them if you need to free up usb ports to stay below the 15 port port-limit.

macOS can only cope with 15 ports , this was denied by Apple in their infinite wisdom. The port count can be quickly reaches given usb 3 and usb-c ports take up more than port, for example every usb 3 port has 2 entries in the map. One time for usb 3 and one time for usb 2. I've mapped every single port on the machine with adds up to:

2x usb 3 on the front = 4 entries in the map.
2x usb 3 on the back = 4 entries in the map.
2x internal usb 2.0 header = 2 entries in the map.
1x internal usb 2.0 from Intel combo card = 1 entry in the map.
1x usb-c on the back = 4 entries in the map.

Thats exactly 15 ports. If you connect something to all of them it will still be below the 15 port limit as the ports that have more than one entry can only work in one mode at the time. But it is balance you must keep in mind. You can also test this yourself, attach a few usb hubs and start adding devices until you pass 15 ports in use at the same time. Any new devices plugged in might not work, or work and cause another device to stop working. This can be bad when it's a drive thats being ejected for example.

Lot of text, but it all boils down to if it works for you then it works. Most people will stay well below the port limits but its not impossible to go over it. Thats why I stick to the "rules" and do things by the book. But there are plenty of people who just disable the port limit in the config (```XhciPortLimit```) and only use the USBInjectAll kext and never bother with usb maps. And as long as they within the 15 port limit and their ports are detected properly they will never experience any issues. Problems will arise when macOS detects your usb 3 port as only usb 3 so usb 2 devices simply don't work or the other way around. Lots of other weird issues regarding usb and usb-c can be caused by not having a map.

Some references:

Why you should map usb ports: https://dortania.github.io/OpenCore-Post-Install/usb/
How to map usb ports: https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html

![nuc8i3beh_mainboard-1024x1024](https://user-images.githubusercontent.com/63272687/114361472-74071700-9b76-11eb-8439-d9d8d87ad8cb.jpg)

**Comment by murmeltier08** [comment]
Thank you very much. This help me a lot. Perhaps your picture in the manual with the hint that the HS10 is the intel card help others to understand the reason why this have to change?

**Comment by zearp** [comment]
It's already in there.

![Screenshot 2021-04-12 at 11 18 54](https://user-images.githubusercontent.com/63272687/114371557-e54bc780-9b80-11eb-883d-29327001b4c0.png)

I rather not add even more text as it's easy to get way too verbose, specially when explaining all the why's for everything in the EFI. It'll also make it easier to miss important info. Some things will just be explained briefly or not explained at all. People wanting/needing more in depth info should go over the Dortania guide as it does a much better job than I can do lol.

I've [clarified it](https://github.com/zearp/Nucintosh/commit/a44813958b16d53d5f44a3ea2f91568c19af6330) a bit, but thats all I will do. I didn't start this repo to become a document writer or to teach people. It's purely meant as a way to get things going quickly and properly on a Coffee Lake NUC. I like to keep things simple and plain. For that reason I also don't include or setup any GUI for OpenCore. Those are all things people can do themselves if they want.

**Comment by murmeltier08** [comment]
Your editing is enough. And this issue will help if someone is interested in additional information. Thank you very much.
