### ISSUE TITLE
Question regarding native Apple WiFi/BT.

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#49]
Hello,

In your guide you describe _You'll also want to set your region to #a as it allows for full 80mhz channel width on ac cards. It might not be 100% legal depending on where you live. I've used this method on a few DW1820A cards and the speed increase was pretty amazing. This method may also apply when using real Apple cards, you will need add AirportBrcmFixup on 1st party cards. To change the region simply add the following boot flag brcmfx-country=#a._

My questions are:

1. Why do we need AirportBrcmFixup on original Apple cards? (I've got BCM94360CS2)
2. When you say "may apply", does it actually apply? (should I do it?)
2. Is the boot flag the only thing required, or does AirportBrcmFixup need to be recompiled with the proper region?

Thank you for any input.

PS. I envy your Akasa case lol

**Comment by zearp** [comment]
Depending on the region the channel width may be listed to only 40mhz. This reduces speeds quite a lot on ac connections. Setting the region to #a allows for these channel width. Using 80mhz channels may not be legal everywhere, if you're in such an area you router may not even support 80mhz to begin with. Just a thing I'd like to mention but realistically nobody has to worry about.

1: Without this kext you can't change the region of the card, Apple will set the region to whatever it thinks is the correct one. Sometimes using regions set my routers around you.

2: I don't know what region you're in, I like using #a because even if its allowed to use 8-mhz it doesn't always work properly. With region set to #a it always works just fine and you will get the max wireless speeds.

3: The boot flag is required to change the region yes. You can also add a section in the DeviceProperties in the config you prefer that. 

Either way, check if you need it before doing anything. Hold down the alt key while clicking on the wireless icon and it will show the details of the connection. Also keep in mind your router needs to support 80mhz width too. Some other less important things also "unlocked" with region #a such as all the 2.4ghz channels.

Th case has ben alright, without undervolting it can overheat when stress testing though. My other NUCs are in their stock cases. The Akasa is not cheap lol. But worth it as a 100% silent daily driver for personal use. The NUCs do make great little hacks. 

I've seen some people desolder the card reader and install a little socket for another m.2 device. Too and my soldering skills suck cuz its a nice hack, specially since the sd card reader is pretty useless for us in macOS. Too slow and unreliable.

I'll add a little note about checking if you need to set the region or not. I just always do it so I don't have to worry about it anymore.

**Comment by naryfa** [comment]
Hey, thanks for such a fast response. 

Great tip with the Alt key and the wireless icon, I didn't know that. You were right, I don't need to change anything. It is showing 80MHz and the Country Code as US.

I was going to order the Akasa case, but I painted my NUC white... I'd have to paint Akasa too. I'm in love with the fanless design. My NUC is currently on the monitor's VESA mount, so at the very least I have zero desk space penalty. :)

Thank you for the great effort and work on the EFI, it's so much easier than 2 years ago with Clover!!!

**Comment by zearp** [comment]
Ohh that all sorted then! Each region has certain allowances in regards to available channels and such. It can lead to weird issues when Airport cards set themselves to a wrong region. I've had my iPhone do this for a while and it couldn't see my own network unless I used certain 5ghz channels. Either way everything looks good on your side!
