### ISSUE TITLE
Boot loop due to apfs snapshots that cannot be deleted

### ISSUE THREAD

**Issue by qeternity** [zearp/Nucintosh#5]
Hi mate - thanks a million for this repo.

Using the latest master against a fresh Big Sur B10, I'm getting stuck in a bootloop. The sealed root apfs volume can't be mounted, and booting into recovery and deleting fails due to insufficient permissions. I've spent a couple hours trying to find what the root cause is but these error messages seem pretty new. Also, post install the main partition isn't bootable.

**Comment by zearp** [comment]
I have yet to try beta 10 but sometimes it is indeed very troublesome to get rid of these weird boot issues caused by snapshots. What happens sometimes it formatting the disk in Catalina and not the installer. I've also found upgrading Catalina can sometimes resolve these issues (and introduce new ones like UI elements being blank until you toggle dark mode). Be sure to use the latest OpenCore from here, I think yesterday or the day before they added some fixes for b10. I've uploaded a fresh build not too long ago that includes those commits.

Another option is to install it and not do any sealing/snapshots. A project called [big-sur-micropatcher](https://github.com/barrykn/big-sur-micropatcher) can patch the installer and it disables sealing and I think also snapshot creating by default. There quite a few neat thing the patcher can do. Check out their project if you wanna try that method.

As to fix your boot loop, I dunno if this is due to b10 or something else. I've also ran into your permission issue once or twice. I'll have to try it later with a clean install of b10 and see if I run into a same again. I've did many clean installs and even when using the same beta sometimes I end up with unfixable error 66 then when I reinstall the same version form the same usb stick everything works. It's a bit of black magic lol. Lets hope Apple can iron out these bugs before the GM. On my supported Macs it is also buggy when doing clean installs.

**Comment by zearp** [comment]
Just tried a clean install b10, everything installed ok but then once it's done I also can't boot into it. I got a few panics but now it just halts right after loading the kernel without an error or panic on screen. No clue what causes this. The last clean install I did was b8 and that went ok some of the times and broke some other times. I'll investigate further but don't wanna sink too much time in Big Sur as things can still change quite a lot before the GM drops. If you find a way around it let me know!

**Comment by qeternity** [comment]
Legend. Thanks for giving a go. At least I know it wasn't me. This is my first NUC build and my first OpenCore so good to know. This repo is awesome, so I will definitely pitch in keeping things as plug-n-play as possible. However I think you're right: with APFS, Apple Silicon and T2 changes it's probably not worth keeping pace with the betas. I'm going to install Catalina to this NUC tomorrow and wait for Big Sur to hit GM.

**Comment by zearp** [comment]
You're welcome! You got the plug-n-play part right. I try to keep this repo basic and working with what the NUC comes with. It should work on a fresh machine with basic bluetooth/wireless. I've added steps for when you've added an Airport card (which I personally did on mine),but my goal is to provide a base EFI that "just works" on any new NUC.

Yeah, for production/stability Catalina is best for now. I've been running these little NUCs on Catalina for months and haven't had any freezes or instability and I push them quite hard from time to time.

It's fun to try the beta's but even on my supported Macs they're not as stable or fast as Catalina is on them. The APFS changes are also a show stopper for me. Not being able to make bootable clones is caused by those changes. Can't even use Apple's own tools to do it haha. No cloning = no daily driver.

**Comment by zearp** [comment]
@qeternity I figured out the cause of the panic, at least the one I ran into. I can not do a clean install of b10 using the current EFI on the repo and setting ```SecureBootModel``` to disabled. Let me know if this also worked for you.

**Comment by zearp** [comment]
@qeternity I figured out the cause of the panic, at least the one I ran into. I can now do a clean install of b10 using the current EFI on the repo and setting SecureBootModel to disabled in config. Let me know if this also worked for you.
