### ISSUE TITLE
Onboard Bluetooth not working

### ISSUE THREAD

**Issue by cangurellobello** [zearp/Nucintosh#51]
Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
  Simply fresh install BigSur on nuc8 and paste latest oc 

- macOS version and optionally the build number
  BigSur 11.4

- Any changes you made to the config and/or EFI other than serials/etc
  no changes

- Any logs related to the issue if applicable
  none

**Comment by ajai-akkarapaka** [comment]
Thank you so much for your support Zearp. Anyways, the bluetooth kext is not working with the stable release. Therefore downloaded the bluetooth kext from https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/tag/v2.0.0-RC1 and replaced it in the EFI. It works.

**Comment by zearp** [comment]
All the bluetooth kexts do is load the Linux firmware. I comply it from source with only the firmware we need for this chip. I will update it again if its broken now. I couldn't test it cuz my NUCs are on Catalina or Monterey and/or have Airport cards. Don't have any with Big Sur but will do a clean install of that tomorrow after updating the bluetooth kexts, which I will do now. There's not much else we can do.

**Comment by zearp** [comment]
All the bluetooth kexts do is load the Linux firmware. I compile it from source with only the firmware we need for this chip. I will update it again if its broken now. I couldn't test it cuz my NUCs are on Catalina or Monterey and/or have Airport cards. Don't have any with Big Sur but will do a clean install of that tomorrow after updating the bluetooth kexts, which I will do now. There's not much else we can do.

**Comment by zearp** [comment]
Can anyone check if these work in Big Sur? Just compiled it from the latest source. I prefer to compile my own cuz the releases have like 20-30 firmwares inside making the EFI huge.

[IB.zip](https://github.com/zearp/Nucintosh/files/6722200/IB.zip)

**Comment by zearp** [comment]
Oh seems the release of the 2.x branch is a lot smaller. I recall the kexts were becoming quite large due to all the firmwares inside. Like 10mb+ for just the kext with the firmwares. Either way, I'd still wanna compile my own cuz its part of my build process and would take more time to download and copy it in manually.

**Comment by zearp** [comment]
Installing Big Sur now on a 120gb ssd I found. Will keep Big Sur on there so I can boot into a clean Big Sur to test stuff if needed again in the future. I admit I have neglected Big Sur because I kind of dislike it. Focussing mostly on Monterey now.

I do have 1 NUC with Big Sur but the Intel bt/wifi on there is useless cuz I snapped the antenna connectors off when trying to disconnect the antenna's 😅 

They are really, really fragile and I am very careful with these things and they snapped off regardless lol. It only happened on one so maybe it was dodgy to begin with.

**Comment by zearp** [comment]
Yeah, no bluetooth, even when compiled form the latest source which on paper should be the same as the RC release linked above. I'll wipe and clone their repo and compile again. Very strange indeed.

**Comment by zearp** [comment]
Fixed in https://github.com/zearp/Nucintosh/commit/a28e505ae0a55cda950d145a51fd2948b55db5d1

Somehow even though the kext loaded it didn't load the firmware itself. Deleted my clone of the repo and cloned and compiled it again and now it works. I have no clue why. It shouldn't have broken in the first place haha. I will test better next time, shouldn't have assumed it would work.

(In my defence I use remote desktop a lot and where I use bluetooth its on Airport cards cuz only those support HID proxy. A feature I can't do without when it comes to bluetooth keyboards and mice. Pair them once in macOPS and they work everywhere else too. Such a nice feature, I am a fan lol.)

**Comment by ajai-akkarapaka** [comment]
Fixed.. It's working now. Thanks again
