### ISSUE TITLE
Has anyone been able to install the Monterey Beta 2 update?

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#52]
Mine just returns to Update Available in system prefs...

**Comment by zearp** [comment]
No logs? What does verbose boot show? Also keep in mind this a beta and I can't really provide support cuz it might be hard to figure out if this happens due to something the EFI or if it's just an Apple bug. Either way when you open an issue please provide as much information as possible, at the very least some logs or what error it gives and where.

I haven't tried beta 2 on my NUCs yet and I might skip this build cuz beta builds will keep coming out every 7-14 days now and things will change and it might turn out the issues we spend a lot of time in trying to solve were just Apple bugs and end up wasting our time.

**Comment by zearp** [comment]
No logs? What does verbose boot show? Also keep in mind this a beta and I can't really provide support cuz it might be hard to figure out if this happens due to something the EFI or if it's just an Apple bug. Either way when you open an issue please provide as much information as possible, at the very least some logs or what error it gives and where.

I haven't tried beta 2 on my NUCs yet and I might skip this build cuz beta builds will keep coming out every 7-14 days now and things will change and it might turn out the issues we spend a lot of time in trying to solve were just Apple bugs and end up wasting our time. Also, how did you install? Only via Software Update or did you also with a full installer app or with a full installer usb stick?

**Comment by zearp** [comment]
No logs? What does verbose boot show? Also keep in mind this a beta and I can't really provide support cuz it might be hard to figure out if this happens due to something the EFI or if it's just an Apple bug. Either way when you open an issue please provide as much information as possible, at the very least some logs or what error it gives and where.

I haven't tried beta 2 on my NUCs yet and I might skip this build cuz beta builds will keep coming out every 7-14 days now and things will change and it might turn out the issues we spend a lot of time in trying to solve were just Apple bugs and end up wasting our time.

Also, how did you install? Only via Software Update or did you try with the full installer app or with a full installer usb stick too?

**Comment by naryfa** [comment]
Only via software update. OK, I'm sorry.

PS. I wouldn't know which logs to look at.

**Comment by zearp** [comment]
I assume you have the EFI as stock so it should show messages when it's booting. It might scroll by really fast and then automatically reboot. In that case you can either setup some debug boot logging or use your phone to film it and scroll the timeline of the video to see what happened. I usually use the latter as its fastest.

On my Dell hacks the updater fails due to some SMC error. Maybe the same happens here, I haven't tried yet. The apparent fix (it isn't done updating yet) is to use the full installer app or install stick. The smaller updater you download via Software Update may have issues. Till now the update been going well after making and using an installer usb stick.

**Comment by naryfa** [comment]
I will make a USB stick and try to install from that. If it doesn't go well, I'll record with the phone.

PS. My EFI has BT, WiFi and ...NVMe kexts disabled. I use original Apple card with adapter via the PCIe/NVMe port.

**Comment by zearp** [comment]
Ah cool, I have some with those as well, it sucks to give up NVMe for some tasks, for day to day usage a fast sata ssd will do just fine. Specially ones with good random i/o performance. I'm running an upgrade from Big Sur to Monterey on a NUC. Might try a clean install later. Normally don't really bother with beta until public beta's come out but I wanted to try out the new features like Airplay sharing. Which worked great!

Oh, I remember seeing some Chinese NUC8 users desolder the sd card reader and put on an adapter to use it as another pci interface for wifi/bluetooth and keep the m.2 slot free for NVMe. My soldering skills aren't good enough for that but it is an option if you're up for it haha.

**Comment by zearp** [comment]
Beta 2 seems to break SMC related stuff. Beta 1 works perfectly fine. We may need to wait for VirtualSMC updates or some other supporting kexts or OpenCore itself. Cuz I have no clue why it complains about SMC. It did the same on my other hacks. I'm temped to try it on MacBook but I'm done for now installing Monterey, got an overdose today lol.

**Comment by zearp** [comment]
Beta 2 seems to break SMC related stuff. Beta 1 works perfectly fine. We may need to wait for VirtualSMC updates or some other supporting kexts or OpenCore itself. Cuz I have no clue why it complains about SMC. It did the same on my other hacks. I'm temped to try it on MacBook but I'm done for now installing Monterey, got an overdose today lol.

I tried the usual to bypass the SMC error; disable compatibility checks, set VirtualSMC flags to load on beta's and some others. But nothing did the trick. I didn't try other SMBIOS, I don't know what other matches would be good other than the 2018 MacBook Pro which has the same chipset and cpu's and the NUC 8 series.

Maybe this weekend I'll try different SMBIOS if there's no fix out yet, I'm guessing I'm not the only one running into this error. The config here works perfectly fine with beta 1 and any previous macOS so I blame Monterey bugs/changes.

**Comment by zearp** [comment]
Quickly tried MacBookPro15,2 but ended up with the same error; we don't support SMC on this platform.

**Comment by naryfa** [comment]
Me too. I borked my setup. Had to reformat and decided to put back Mojave until full development is complete.

PS. What are your boot times on NUC?

**Comment by zearp** [comment]
Beta 2 successfully installed using latest config/build on the repo (or attached EFI.zip) and ```SecureBootModel``` set to ```Disabled```. Only tested clean install. Importing files/settings from a backup using the macOS migration tool works as intended. Make sure to clear nvram before doing a new clean install.

![Screen Shot 2021-07-04 at 04 53 27](https://user-images.githubusercontent.com/63272687/124371682-8af46b80-dc84-11eb-9a1d-e8c54631467d.png)

[EFI.zip](https://github.com/zearp/Nucintosh/files/6759303/EFI.zip)
