### ISSUE TITLE
Question about the charging port.

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#54]
Hello, 

I noticed that enabling the NUC's charging on USB port doesn't have any side effect (at least after OS installation). Has anyone reported anything?

**Comment by zearp** [comment]
No report no. I think the rationale is that it messes with the power management, we set certain power limits with USBPorts.kext and sometimes with ACPI patches (not needed for Coffee Lake). I got those things from Rehabmans initial work on the NUC 7/8 platforms. He didn't document much of the reasons but there's a lot of info to be found in his patches.

Many of the things he had to do may no longer be needed due to advancements and things like OpenCore. I should maybe revise it but I don't really know if maybe in some edge cases things suddenly act weird. I just know Rehabman was good at what he did and wouldn't disable stuff that isn't strictly needed. Have to see if any of those changes result in a different IOreg dumps or something like that.

The same applies to the WOL setting. Everything is fine with it left on but I can't get WOL to work though, even when compiling my own IntelMausi kext with WOL enabled. I really want to get that work but its above my pay grade at this point lol.

https://github.com/RehabMan/Intel-NUC-DSDT-Patch

**Comment by naryfa** [comment]
Would you have the time and will to test it on your NUC? Or are you too busy to investigate that?

I so far had no problems.

**Comment by zearp** [comment]
I can enable and see what happens, dunno what else to do.

I've never used this feature on anything I own (charging a device with a pc/laptop when it's turned off). I did notice that even after a shutdown the ports keep giving power even with the bios option disabled. Not sure if its enough power to charge something but sure is enough power to keep the led on my usb sata interface on. I think I also still have WOL enabled on one of them and no problems so far.

If you have time to dig trough the Rehabman patches and see if you can find clues as to why things should be on or off that would help. I don't have enough hours in the day to do a lot of reading and mainly want to focus on proper UEFI secure boot and WOL next. Another route would be to find out what exactly these bios options change. What changes in the h/w profile or ACPI or wherever it's doing its thing. Intel might have documented it but I couldn't find much when I looked into it. There's a more in depth technical manual but nothing useful for this kind of depth.

https://github.com/zearp/Nucintosh/blob/master/Stuff/NUC8i3BE_NUC8i5BE_NUC8i7BE_TechProdSpec.pdf

There's an excellent guide for the Hades Canyon NUC which is not very similar to ours but does have about the same BIOS. They say turning charging on and leaving a device in the yellow port would prevent the NUC from sleeping.

https://osy.gitbook.io/hac-mini-guide/installation-guide/bios-settings

Can you check if thats also true for ours? It might apply to all NUCs with this feature.

**Comment by naryfa** [comment]
First of all... I just used the freshest EFI you uploaded and I'm super-grateful. **Thank you**.

I've read the NUC manual, perhaps not thoroughly, but with a decent attention to detail.

The second link you gave I checked out and it kind of makes sense. 

Here's my test on the NUC **when nothing is connected to the yellow USB port**. 
--- Charging in BIOS set to 'Disabled' - system will sleep properly
--- Charging in BIOS set to 'Charging Only' - system will sleep and wake up after 2 seconds
--- Charging in BIOS set to 'Chariging in S3/S4/S5' - system will sleep and wake up after 2 seconds

**When anything is plugged into the yellow port**, no matter which USB charging BIOS option is chosen, the system will go to sleep and wake up after two seconds. 

The Intel BIOS (when hovering over that field) says that the yellow port provides highest possible current. So, it may have something to do with it.

I'll just leave the charging on. I prefer to charge my phone when the system is off. I never use sleep.

I'm closing the issue, thank you for help. Perhaps someone will find it useful.

PS. Hope you get the WOL to work.
