### ISSUE TITLE
Long Scan and TRIM upon boot

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#59]
As in the subject, any help is appreciated. The SSD is an Intel SATA 530 Series 480GB, like the one in the link:

[https://ark.intel.com/content/www/us/en/ark/products/75336/intel-ssd-530-series-480gb-2-5in-sata-6gbs-20nm-mlc.html](url)

Please provide the follow information:

- Steps to reproduce the issue -- this is crucial:
REBOOT

- macOS version and optionally the build number:
10.14.6
EFI_05072021

- Any changes you made to the config and/or EFI other than serials/etc:
Disabled the following kexts: Airportltlwm, IntelBluetoothFirmware, IntelBluetoothInjector, NVMeFix, 

- Any logs related to the issue if applicable:
See attached photo
![IMG_2978](https://user-images.githubusercontent.com/38587586/129396379-dfe056ed-f71f-43f4-a11d-d5631127f5e3.PNG)

**Comment by zearp** [comment]
Slow/odd behaving drives is related to the ssd in combination with macOS itself, not the config or EFI unfortunately. 

The options you have are to disable trim and see if that helps. This would require your drive to trim itself or things may become slow over time. Normally trim happens when it's needed and shouldn't happen on each boot if it causes a long delay. You dint' say how long the delay is. With ssd/nvme the disk either works well or it doesn't. It can be hit and miss even within certain brands. For example the Intel 600p is a trouble maker whilst the 660p works fine.

To turn off trim search for ```ThirdPartyDrives``` in the config and disable it then reboot and verify trim is disabled in the System Information app. It may also be needed to run ```sudo trimforce disable```. Maybe it goes better with trim disabled.

You can also try booting into recovery and running firs aid checks on the disk, maybe there are some errors that cause this. If you have more disk you can make a backup and restore it after formatting it. Maybe there's some "garbage" laying around that isn't sorted by trimming.

If none of that works then I don't think this can be fixed and you have to live with it or use another disk and keep the Intel for backups and such.

I'm using mainly Samsung drives and some crucial myself and have no issues with them, either with trim on or off.

**Comment by naryfa** [comment]
Understood. Thank you very much for the input. I did provide the delay info, though. The highlighted part on the screenshot shows how long it is - mainly 81 seconds for scan and 80 seconds for TRIM.

I will disable the TRIM in the config as you specified and will report back on it (if _ sudo trimforce disable_ is necessary will perform that also).

I love these drives as they're MLC, but then again - anything can fail prematurely for a myriad reasons.

**Comment by naryfa** [comment]
It was enough to disable ThirdPartyDrives. The entire reboot took maybe 12 seconds total, it went smoothly after the last FIPSPOST_USER, which is where it used to hang. No _sudo trimforce disable_ seemed necessary. 

At this point I declare this to be solved. If possible, please don't delete the post for future reference.

Thank you so much for your help. You've been golden!

**Comment by zearp** [comment]
Oh sorry I missed that, yeah over a minute isn't right. I wonder why Intel disks have these odd issues. There was another issue not too long ago with another Intel model. 

I think it might have to do with the controller inside the disk. Thanks for the details, good to know just in case someone else runs into something similar.

I will do some tests with other brands I got laying around and see if I can reproduce it too. Maybe I lucked out with Crucial and Samsung using a controller that works good with macOS own trim stuff.
