### ISSUE TITLE
Installing Monterey stuck in boot loop.

### ISSUE THREAD

**Issue by JaseNZC** [zearp/Nucintosh#60]
You may or may not be able to answer this but when upgrading or doing a clean install of Monterey I get stuck in an installation loop.
Process followed.

Created installer changed efi to recommendations for Monterey as per git here.
Installer starts fine, Format nvme drive and proceed with install.
First part of install is fine says taking 20 mins etc
Reboots then goes to main install which says taking 29mins ect.
This also run's fine and reboots.
Uefi is showing Mac os installer but there is where it loops in the installation. 
It does not seem to close off the install partition and the finally boot from the name of the drive you gave it when formatted.

Any idea's ??

Installer would be public beta 5 which I think has only come out.

**Comment by zearp** [comment]
Try setting ```SecureBootModel``` to ```x86legacy``` instead of disabled.

To catch what exactly happens you can record the screen with your phone and scroll the time line afterwards. But I think since beta 5 disabling ```SecureBootModel``` causes issues. I also had some issues with set to disabled. They're beta's so many beta 6 will use another issue somewhere lol.

Till Monterey GM I don't really want to on supporting the beta here. Things change and break during this cycle and I don't really wanna spend too much time on it until it's final.

Do let me know if the change fixes it. I only did an upgrade to beta 5 so far, not a clean install.

**Comment by zearp** [comment]
Try setting ```SecureBootModel``` to ```x86legacy``` instead of disabled.

To catch what exactly happens you can record the screen with your phone and scroll the time line afterwards. But I think since beta 5 disabling ```SecureBootModel``` causes issues. I also had some issues with set to disabled. They're beta's so maybe beta 6 will cause another issue somewhere else haha.

Till Monterey GM I don't really want to support the beta here. Things change and break during this cycle and I don't really wanna spend too much time on it until it's final.

Do let me know if the change fixes it. I only did an upgrade to beta 5 so far, not a clean install.

**Comment by JaseNZC** [comment]
Yeah I have re-installed Big Sur which went fine.

Gonna pull out another drive tomorrow and have another play with beta 5

I know where you are coming from re the beta's there is no point until release.
