### ISSUE TITLE
Unable to upgrade beta version.

### ISSUE THREAD

**Issue by legendhb** [zearp/Nucintosh#61]
Please provide the follow information:

- Steps to reproduce the issue
  1. System noticed that new beta version of macOS(Beta 5) was available;
  2. Clicked "Download & Install", system rebooted;
  3. System would not upgrade to beta 5, still stayed on beta 1.

- macOS version and optionally the build number
  Currently Monterey Beta 1 (21A5248p)
- Any changes you made to the config and/or EFI other than serials/etc
  No

**Comment by zearp** [comment]
I have no issues with the newer beta's but the earlier ones were buggy with updates. Best is to do an upgrade using a full installer and install on top of the existing macOS, after making a backup of course. I can't provide any support for beta's tbh. They're moving targets that can break and do break form time to time.

**Comment by vardumper** [comment]
I think you might need to clarify the Monterey notes a bit. While modifying that SecureBoot to Disabled is clear.
, I did not understand what you mean by Replace IntelBluetoothInjector with BlueToolFixup. What I did was remove IntelBluetoothInjector, paste in BlueToolFixup and then renamed it to IntelBluetoothInjector. Then I also needed to adjust or add the ExecutablePath since it's called BlueToolFixup not IntelBluetoothInjector. Did I do that correct?

Before that I was unable to install at all. Either Bootup took 20mins, just so that the installer did not see my internal drive SSD, or the system hang. With the SecureBoot setting I could boot and install normally, but am now experiencing Bluetooth problems. Which sucks because I don't have a cable mouse nearby.

**Comment by zearp** [comment]
For newer beta's setting to x86legacy might work better, I will migrate everything to Monterey as soon as its released. As for swapping the kexts, I sort of assume people use the ProperTree snapshot function and I never really intended this to be super beginner friendly, some knowledge is needed but I will see if I can clarify it when rewriting the readme file after Monterey is out. Thanks!
