### ISSUE TITLE
stuck on [EB|LOG:EXITBS:START] when using oc 0.7.4 and 0.7.5

### ISSUE THREAD

**Issue by occparty** [zearp/Nucintosh#70]
Deer Zearp,

In the beginning I deeply appreciate your work on this nuc hackintosh. I have same NUC8i5beh and BIOS at version 89, with all your recommend setting in it. Every time with your quick OC update the machine is reliable;  now this NUC is on Monterey 12.0.1. (upgraded from big sur), thank you!

I encounter that the booting process recently stuck on [EB|LOG:EXITBS:START] when using oc boot loader 0.7.4 and 0.7.5 your newest version. BUT it can boot normally into macOS system with your 0.7.3 version without issue.

I've done comparing 0.7.3 and 0.7.5 and only notice there are few change including:

- booter-quirks-ResizeAppleGpuBars ( newly added)
- misc-security-SecureBootModel (changed from j174 to x86legacy, the oc default value)
- UEFI-quirks-ResizeGpuBars (newly added)
- and the BlueToolFixup.kexts

I've tried Dortania's Guide about Kernel Issues and do some adjustment on EnableWriteUnprotector and DevirtualiseMmio but all resulted in vain. 

Also I tried setting SecureBootModel value to "Disabled", still get the same result.

Can you please give some hints? Thank you!

--------------------------------------
Please provide the follow information:

- neither 0.7.4 and 0.7.5 is stuck on [EB|LOG:EXITBS:START]
- macOS Monterey 12.0.1
- NO, I use your kindly default setting
- logs here ( the last one is setting SecureBootModel value to "Disabled" )
[opencore-2021-11-05-075245.txt](https://github.com/zearp/Nucintosh/files/7481586/opencore-2021-11-05-075245.txt)
[opencore-2021-11-05-080023.txt](https://github.com/zearp/Nucintosh/files/7481587/opencore-2021-11-05-080023.txt)

**Comment by zearp** [comment]
I don't know why you're manually updating or editing the config file. I can't reproduce this issue using the latest release.

The fix is very easy.

1: Remove all EFI folders, make a backup of your config to cope the serials/mac address back from.
2: Download the latest release and put it on the EFI folder.
3: Copy your serials from your backup into the config file

That should be it, it is the best way to update the EFI. 

I can't help troubleshoot why it's not working for you. The current release works fine for Monterey installations. If you want a newer version for whatever reason you're on your own. I will update the repo when I want to or when it's needed. Currently everything works fine. I used to do a weekly release on Sundays but I'm quite busy and as I said the current release works fine. I can only help with issues relating to the EFI that's in the release section.

**Comment by zearp** [comment]
https://github.com/zearp/Nucintosh/releases/tag/v3.1



I'm not going to do this every week anymore but I needed to update it for bluetooth fixes. I have not encountered them myself but some others did and there are new commits to the fixup tool. so hopefully this solves their bluetooth issues.

If you need to be on the latest greatest versions of OpenCore and the kexts  you have to build from sources yourself. I'm not going to update the repo for each commit made to one of the kexts or OpenCore.

I will push changes from time to time without making a new release, I only release something I tested. But it would be fine to use a current snapshot of the repo. Always update using the serial copy method. The config file has been a moving target since I started using OpenCore.

**Comment by zearp** [comment]
This release boots fine into the installer. It will complete the installation and it will also boot the installed macOS properly.

These are standard tests I do for every release, I hope NVRAM and start fresh on a test NUC. But they are getting too time consuming to do clean installs to make 100% sure it works on an unmodified NUC.

So releases and updates will be slower and only done when its really needed. When things work they work. There is no need to be on the latest versions unless it fixes something or improves performance.

**Comment by zearp** [comment]
This release boots fine into the installer. It will complete the installation and it will also boot the installed macOS properly.

These are standard tests I do for every release, I clear NVRAM and start fresh on a test machine. But it is getting too time consuming to do clean installs to make 100% sure it works on an unmodified NUC once a week. Specially when it's not really needed to update anything.

So releases and updates will be slower and only done when its really needed. When things work they work. There is no need to be on the latest versions unless it fixes something or improves performance.

**Comment by occparty** [comment]
Thank you Zearp; finally I figured out that the problem is resulted from propertree. It seems propertree "broken" plist after OC snapshot  ( I have 1st party apple wifi/bluetooth card installed and with your every EFI update I remove the intel related kexts and do an OC snapshot )

I remove the related kexts in plist manually ( without applying OC snapshot) and thus it boot successfully just like before. Again thank you and really sorry for any bothering I may cause.

**Comment by zearp** [comment]
Yes, I have run into the same issue. I had to update ProperTree to the latest version to fix it breaking my config files when using the snapshot feature. I am happy you have fixed it!
