### ISSUE TITLE
Reading out and controlling fan speeds

### ISSUE THREAD

**Issue by gtrooper** [zearp/Nucintosh#8]
Hi ! I wanted to say a huge thanks for your amazing work ! I am in the process of testing everything you did and I must say that your work is truly unique ! I really loved the idea of underclocking ! I can see my NUC8i7BEH behaves differently under pressure and is silent with your CpuFriendDataProvider Kext ! No noticeable performance loss really ! In the next few weeks I will also test some Thunderbolt Apollo Music Interfaces as well some thunderbolt monitors and let you know ! Just one question... Do you know if there is any way to control the FANS of the NUC8 inside macOS ? Thank you for everything ! Really Appreciated !

**Comment by zearp** [comment]
I haven't really looked into fan control or even reading out the fan speed since my main NUC is passive but I have some others that I can test with. Will look into it and see if there's anything to be done. I use my for audio work as well hence the expensive passive case, the guarantee of silence is worth it for me and it performs better than stock.

The change is base clock helps keep things a bit cooler, I also use VoltageShift for undervolting which helps cool it a few more degrees. All in all on both my passive and actively cooled NUCs I can't notice any difference in performance with a lower base clock and undervolting and stock.

I'm not sure if I remember which one it was but when I tried some different SMBIOS a MacBook Pro one that has he exact same cpu as the NUC ran at lower base clock already. The speed ramps up as soon as needed with the current profiles. I've did some A/B testing with and without CPUFriend and he only difference was lower temps and a bit less power consumption. You could remove them if you prefer a very clean EFI but personally I prefer it like this.

Thanks for you kind words and feel free to share you experiences, thunderbolt devices should work. Looking forward to your audio interface testing. I've only tested some usb 3 interfaces and they worked as expected. Don't have any thunderbolt audio gear (yet) haha.

**Comment by zearp** [comment]
I haven't really looked into fan control or even reading out the fan speed since my main NUC is passive but I have some others that I can test with though. Will look into it and see if there's anything to be done. I use mine for audio work as well hence the expensive passive case, the guarantee of silence is worth it for me and it performs better than stock.

The change in base clock helps keep things a bit cooler, I also use VoltageShift for undervolting which helps cool it a few more degrees. All in all on both my passive and actively cooled NUCs I can't notice any difference in performance between a lower base clock and undervolting or stock.

I'm not sure if I remember which one it was but when I tried some different SMBIOS a MacBook Pro one that has he exact same cpu as the NUC ran at lower base clock already. The speed ramps up as soon as needed with the current profiles. I've did some A/B testing with and without CPUFriend and he only difference was lower temps and a bit less power consumption. You could remove them if you prefer a very clean EFI but personally I prefer it like this.

Thanks for you kind words and feel free to share you experiences, thunderbolt devices should work. Looking forward to your audio interface testing. I've only tested some usb 3 interfaces and they worked as expected. Don't have any thunderbolt audio gear (yet) haha.

**Comment by gtrooper** [comment]
Hi again ! Due to some availability issues with Thunderbolt Apollo Music Interfaces I had to ask for a refund and thats why I still have not been able to test this yet ! So far, Thunderbolt-wise, I have tried only a ThunderBolt SSD Samsung X5 and had no issues. But I am really looking forward to test Thunderbolt monitors as well as some Thunderbolt -To-Dual HDMI Display Adapters... Due to Covid-19 the shipping dates are out of this world and will take some time but I will come back when I am ready ! I continue to test every EFI you upload and everything seems way too smooth ! Thanks !!! One question: Have you tried to enable Hand-off and Airdrop on the NUC ? I saw that Intel WiFi and Bluetooth Kexts state that support it but it does not show up in preferences ! Thank you for everything !

**Comment by zearp** [comment]
I have quickly tested continuity features using the onboard Intel wifi/bt card and only some of it worked and its been a while since I tried. I added Airport card in my NUCs. Mainly cuz I use bt keyboard/mouse combo's and with Apple cards those also work outside the OS.

You can try enabling the ```ExtendBTFeatureFlags``` quirk in the config, which might help enable some the features. It may enable some more but it's mostly dependant on the driver. I keep the drivers up to date to the master and compile from source. Try downloading the repo instead of using a release to test with.

As for the fans, even in Windows I've not been able to control the fans. On Windows HWiNFO64 doesn't even pick u the fans. On other machines I can see the fans and control them with that software. I think Intel isn't exposing any type of fan control outside of the BIOS. Luckily it does allow for some very fine grained tuning of the fan profiles.

**Comment by zearp** [comment]
I have quickly tested continuity features using the onboard Intel wifi/bt card and only some of it worked and its been a while since I tried. I added Airport card in my NUCs. Mainly cuz I use bt keyboard/mouse combo's and with Apple cards those also work outside the OS.

You can try enabling the ExtendBTFeatureFlags quirk in the config, which might help enable some the features but it's mostly dependant on the Intel driver. I keep those up to date to the master and compile from source. Try downloading the repo instead of using a release to test with.

As for the fans, even in Windows I've not been able to control the fans. On Windows HWiNFO64 doesn't even detect the fans. On other machines I can see the fans and control them with that software. I think Intel isn't exposing any type of fan control outside of the BIOS. Luckily it does allow for some very fine grained tuning of the fan profiles.

Thunderbolt will get some updates in the next few days, already implemented some half badly in the current repo. But that will change again soon. I been testing flashing and restoring the Thunderbolt firmware and am really close in making it pretty easy to switch between normal and modded Thunderbolt firmware. With the firmware modded Thunderbolt will be working 100% in macOS. Including hot-plugging. On my test NUC after modding I now see 1 Apple Thunderbolt controller with 40gb/s bandwidth.

**Comment by zearp** [comment]
@gtrooper I've updated the repo to include new Thunderbolt stuff. Could you check if your Thunderbolt devices still work for you with the latest release? I'd like to know if everything you used still works on this version as I replaced the previous patch with a new one.

Things should still work as they did before but now you have the option to patch the firmware. You don't have to patch anything, but if you're up for it that would be great. Either way your results with and/or without patching will greatly help. I can only do so much testing on my own.

**Comment by zearp** [comment]
Ignore me closing it, I just can't fix the fan stuff 😅
