### ISSUE TITLE
MacOS Ventura

### ISSUE THREAD

**Issue by TwEnTy90** [zearp/Nucintosh#82]
Hi, My friend! How are you? I would ask il it possible to install Ventura in nuc, can you provide us an efi stable for it? My Russian friend Say hi to you! 

Thank's for your work!

**Comment by zearp** [comment]
Yes, once Ventura is out of beta I will start testing and release a new EFI when everything works. I left a big note on the repo last week about it. Last time I kept following the beta's and wasted a lot of time because Apple changes things around and some kexts needed fixes. 

The current EFI might work fine with Ventura beta's. Have you tried it? The public beta will start at the end of this month and then it usually takes another few months before Apple releases final version.

Following beta builds can be fun and educational but I don't want to do it this time around. I did during Monterey and Big Sur. This time I pass. Let me know how you get on!

**Comment by zearp** [comment]
For the brave!

https://github.com/zearp/Nucintosh/issues/84
