### ISSUE TITLE
CPU compatibility between NUC models

### ISSUE THREAD

**Issue by Drag0nFly** [zearp/Nucintosh#86]
Hi,

_(sorry for opening a ticket, but there was no option to contact by other means)_

Firstly; great work on getting all this useful information assembled in one place–strongly considering replacing my ageing Hackintosh as a result of this. I have one question though; as I have been unable to identify the exact model of CPU you are using in your setup. I assume OpenBoot is more versatile wrt. this, but going from previous experience with other OSX bootloaders, SSDT generation et al., I just wanted to make sure that the system(s) I am considering are actually compatible, as this is what I've been struggling with with my existing Hackintosh (a Shuttle SZ87 and i7-4790S); which has a tendency to run into oom-issues or otherwise freeze on a semi-monthly basis.

Going from the TDP spec, and 8th gen i5, I came up with the following “match” (although the base freq is off)–

- Intel® Core™ i5-8365UE (https://www.intel.com/content/www/us/en/products/sku/193559/intel-core-i58365ue-processor-6m-cache-up-to-4-10-ghz/specifications.html)

The other “match” is the 8400H, but here the TDP is off–

- https://ark.intel.com/content/www/us/en/ark/products/134877/intel-core-i58400h-processor-8m-cache-up-to-4-20-ghz.html

Obviously, since many of the 8th gen. NUC models (esp. i5) are no longer in general availability, it would be useful to know if the 9th gen. models are adaptable to your setup (I assume the chipset would be the bigger hurdle). Also, for all other Hackintosh models I've consistently had to replace AppleHDA with VoodooHDA due to audio quality issues (AppleHDA being harsh-sounding); pretty sure the latter is no longer compatible with recent OSX versions.

btw–the actual CPUs in the NUC units I am considering are i7-8565U and i7-8559U.

Appreciate any input (and sorry again for the noise!)

**Comment by zearp** [comment]
All the normal NUC8 models will work with this EFI. Only the special models with different h/w configuration won't work like the HC models or models with Radeon graphics or other h/w changes. The cpu model itself doesn't matter much as long as its 8th gen. As for 9th gen or newer I don't now because I don't own any of them. The h/w is quite different so it will need new ACPI patches for sure and others too like usb and display connector maps. Any NUC8i*BE* model should work without any adjustments.

I have only i5 models, it has the exact same i5-8259U cpu as the 2018 MacBook Pro. I didn't opt to use the MacBook Pro SMBIOS. The Mac mini 2018 is built on the same mobile Intel platform and I think compatibility is better using the Mac mini SMBIOS than a laptop one. SMBIOS controls and does a lot and not having to deal with disabling internal screen stuff and harsher (voltage/thermal/etc) limits saves a lot of time and issues. The 2018 Mac mini is pretty much a NUC with an Apple badge. But it is possible to use the MacBook Pro 2018 SMBIOS.

Personally I wouldn't buy any model NUC brand new right now unless you can get it for the old prices. They are simply too expensive for what you're getting right now. I paid about $250 for my i5 models at the end of 2020. Right now the same models are almost double in price if you can find them. Second hand might be an option. Also keep in mind 9th and 10th gen models have a faster cpu but a much slower gpu. Prices for those are also too high at the moment imho.

As small alternative you could look into Lenovo's ThinkCentre machines. They go quite cheap refurbished for 4th gen or higher. 4th gen is old but Haswell is not bad and NUCs have mobile cpu's while the ThinkCentres have full desktop cpu's. Dell Optiplex also make nice hacks and can be had quite cheap. Just don't get anything older than 4th gen and no i3's as the integrated HD4400 graphics in those is very glitchy in macOS. Some i3's and all i5 or i7 have the HD4600 which is natively supported including Monterey.

Both Optiplex and ThinkCentre systems are made for business and use much better parts than regular consumer stuff. I've been using Optiplex systems running macOS for many many years, from before I made a Github account. They are very hackable. Same applies to Lenovo but I have less experience with them. Both are solid options and probably have some good EFI's available online to get you started and put the finishing touches on to get the max out of these little machines.

I've seen the ThinkCentre M93p around for under $100 with 8gb ram and a little 250gb ssd. I might pick one up if I see another good deal. They are very tiny! 18x18cm and 4cm high with decent connectivity for the size and age.

![Lenovo_ThinkCentre_M93_Tiny](https://user-images.githubusercontent.com/63272687/179371189-41b5b2ca-070c-4773-ab06-001512e98b3f.jpg)

**Comment by Drag0nFly** [comment]
Thanks for the insightful response. (_+1 on the Dell OptiPlex– that was actually my first hack, and was the most hassle-free of them all!_)

I'm also familiar with the m93p ThinkCentre systems from a previous employer, as these were the standard workstations. They are nifty, but can sometimes be a little loud with the small integrated fan, and the ones we used had the thermal (“T” suffixed CPUs inside. Never tried to hackintosh those, since running OSX was not an option in a work setting, and I am not a big fan of DisplayPort-only output (not counting the VGA.) But at least from what you are saying it should not be an issue with multi-output on the NUCs (couldn't get that working on the Shuttle SZ87, OSX crashed every time, and the scripts which handled this were not applicable for recent OSX versions, etc…)

Thanks for clarifying wrt. to CPU compatibility on the NUCs and for narrowing it down to the **NUC8iBEs**–these basically check most boxes (though not all, as I still miss a S/PDIF toslink output and also the option to put in an optical BD-ROM drive–one of the reasons for choosing the Shuttle). But what I am basically after is a _stable_ setup which is also upgradeable without having to ditch the whole installation and do tons of tweaks in the process (as you can probably guess, I am most familiar with the Chameleon/Enoch/Clover setups which, although working, feel like a constant WiP too me. (Then again, I'm more familiar with *nix and Linux bootloaders, and Sun bootloaders, which is probably the reason for my “OpenBoot” typo above;) OpenCore I have yet to test, and I hope it provides a smoother experience (as well as properly working multi-OS boot)

And yes, the system I am running atm. does indeed use HD4600 graphics; which works quite well. USB mapping is still not working properly for some ports (“some” of the time), but frankly I haven't bothered with it. What really irks me the most is that it consistently will hang after s maximum of two months uptime due to either some glitchy memory handling or OOM condition (not related to DIMMs, as these have been replaced, and cooling replaced, etc.)

I also agree that a brand-new NUC is not the way to go price-wise; I just noticed that some retailers did not carry the 8th-gen models anymore. I do some transcoding and other CPU-intensive things which is why I want some extra _oomph_, but the Haswell to Coffee Lake upgrade should probably be a quite nice step-up anyway (and without sacrificing the internal graphics capability)

Thanks again for your detailed answers–they are really appreciated!

**Comment by zearp** [comment]
I wanted a nicer headphone output as I didn't really like the NUCs headphone output both on macOS and Windows it sounded meh to me. So I got myself a cheap little dac box with dual TDA1305T chips. It's an older Philips chip thats used in high end audio gear like Cambridge Audio and B&O stuff. It only goes up to 48khz/16bit but thats not an issue for my usage. It sounds pretty good for movies and music nice as it uses oversampling which sounds very good. But it's party trick is that it also has an optical output. They can be found quite cheap ($15-25).

If you don't need or want any headphone amp stuff you can likely find a board that just has a usb -> optical dac on it. It might even be possible to fit such a little board inside the case using an internal usb header and jerryrig the optical output in the case itself. A quick search made me find a little $10 board with a PCM2704 on it. Powered over usb, optical output and the volume can be adjusted in the OS too. It should be pretty decent!

![PCM2704](https://user-images.githubusercontent.com/63272687/179372828-c8101b1f-9917-4b50-b686-e7159dad62ee.jpg)

There are quite a few boards on eBay/AliExpress/etc that use the TDA1305T, not all have optical output though. I can highly recommend the dual TDA1305T boards if you're into audio stuff, they are cheap and it's nice to have some warmer sounding dac that uses oversampling. I also have other dacs that have way better specs but I always go back to the dual TDA1305T as it just sounds very smooth. I wouldn't use it for any analytical stuff though but for nothing else it is very good value. 

[TDA1305T.pdf](https://github.com/zearp/Nucintosh/files/9126626/TDA1305T.pdf)

You can speed up some transcoding jobs by quite a lot if you can find a compatible gpu. Then you can run the HD4600 in headless mode and use it for encoding/decoding and other tasks. Not sure if that route would be worth it with the current gpu prices but its something that might be worth it. Not really an option for NUCs as you'd need a Thunderbolt e-gpu enclosure. But surely an option for desktop based builds and some older compatible card. You'd also gain full DRM on any macOS before Big Sur. Getting DRM to work on Big Sur and newer is a big pita even with supported cards.

If only Thunderbolt and all other computer part prices would return to normal the NUC would be very expandable. As it stands now Thunderbolt stuff is very costly. Though it can be worth the investment if you really need the expansions. I have an older model CalDigit dock and it's very nice but it was also very expensive, and I bought that one long before the computer prices got all crazy. We do have 4x 10gbit usb3 ports on the NUC8 but thats still 4 times slower than the Thunderbolt port.

No worries and good luck!

**Comment by nicball** [comment]
> Any NUC8i_BE_ model should work without any adjustments.

Not all of them.

My i5 model is actually using i5 8260U, which comes with UHD 620. According to Dortania's guide, an additional device-id field should be added for this iGPU.

Without the id, macOS boots but stays in the textual log screen. I could see logs about docks and other UI stuff. It's like macOS is trying to draw but iGPU is refusing to.

Just mentioning this in case someone is also search for the same issue.

Also, I am using intel WiFi, but as of Sonoma 14.7.5 it doesn't work out of the box. I have to use heliport just like in Sequoia.
