### ISSUE TITLE
Kernel Panic after reset NVRAM

### ISSUE THREAD

**Issue by ThePilger** [zearp/Nucintosh#91]
My Nuc8i3 Hackintosh works fine until i made an NVRAM reset. Now its getting a Kernel Panic. I also tried to redownload the efi folder to boot opencore from the usb but it didn’t work.
![AF1149F7-18A2-42C5-84C6-624D65B21105](https://user-images.githubusercontent.com/111175089/184475859-03c5c812-e05f-41f7-b937-b39c2eee1aba.jpeg)
How can i fix this?

**Comment by zearp** [comment]
Try disabling the NVMe helper kext, it seems to be related to the panic. Resetting NVMRAM should not result in a panic though. I can't reproduce it by resetting NVRAM on a NUC here with an NVMe drive in it.

What happens when you boot form the installer usb stick? Make sure to use the bios boot menu (F10 while booting) to choose a bootable disk.

**Comment by zearp** [comment]
Try disabling the NVMe helper kext, it seems to be related to the panic. Resetting NVMRAM should not result in a panic though. I can't reproduce it by resetting NVRAM on a NUC here with an NVMe drive in it.

What happens when you boot from the installer usb stick? Make sure to use the bios boot menu (F10 while booting) to choose a bootable disk.

**Comment by ThePilger** [comment]
Without the kext i get the same panic, but now it restarts immediately. I will create a new installer usb and reinstall macos. But thanks for your help.

**Comment by zearp** [comment]
Please keep the usb installer if possible so you can boot from it in case the issue returns. Resetting nvram I sometimes needed and it should not result in any panics. I tried resetting nvram on mine and didn't get any panics. Good luck!

**Comment by ThePilger** [comment]
I think there was an issue with the NVME Drive itself. I tried to reinstall Monterey from my USB and there was the same panic, so i formated the NVME with a linux usb and the same MacOS installer usb is working now.

**Comment by zearp** [comment]
Wow! Sounds like something go corrupted somewhere on the disk. Too bad we weren't able to get a full panic log. Would be interesting to see exactly what happened for educational purposes. But I'm glad it is working! I have issues with NVMe drives from time to time too. Either enabling or disabling the NVMe helper kext fixes it and some drives are just incompatible with macOS.

**Comment by zearp** [comment]
Wow! Sounds like something got corrupted somewhere on the disk. Too bad we weren't able to get a full panic log. Would be interesting to see exactly what happened for educational purposes. But I'm glad it is working! I have issues with NVMe drives from time to time too. Either enabling or disabling the NVMe helper kext fixes it and some drives are just incompatible with macOS.
