### ISSUE TITLE
Sudo Trimforce Disable - no effect on SATA SSD

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#97]
Any ideas what could cause the trimforce command to have no effect? Any kexts?

I've got csrutil disabled as well

I generally disable trimforce because it shaves off nearly a minute from the boot time, but on macOS Monterey 12.5.1 (21G83) the TRIM Support in System Report always shows Yes.

**Comment by zearp** [comment]
Set the ThirdPartyDrives quirk to false.

https://github.com/zearp/Nucintosh/blob/master/EFI/OC/config.plist#L629-L630

**Comment by zearp** [comment]
I just noticed you said disabling it shaves a minute of your boot time. My boot time with it enabled is less than a minute. Something might up with your disk if takes a minute to trim the drive. Have you checked the SMART data of the disk? I don't know if I should disable the quirk by default because having trim enabled is quite useful. Specially on disks with shitty chipsets or bad garbage collection.

**Comment by naryfa** [comment]
I will try the quirk. But I did the same thing on the previous SATA drive and it helped. Both are in a perfect state. This one is new. I always use Intel MLC drives. This one happens to be 520 series. Previous was 530.

**Comment by zearp** [comment]
The quirk "force" enables trim on non-Apple SSDs so disabling it will allow the trimforce command again.

No slow boot times for me on any of my NUCs, I have one with a Samsung EVO 860 and the others have Crucial MX500's or NVMe drives.

**Comment by naryfa** [comment]
Will report this evening on any progress, but perhaps the drives you use are equipped with a better controller. Who knows...

**Comment by naryfa** [comment]
There are a bunch of "force" quirks and one array, not sure I understood your last message correctly.

I hope I did the right thing just by setting the ThirdPartyDrives to false

**Comment by zearp** [comment]
Yes that is all. I linked to the part that needed changing above, it should highlight it in your browser (not sure if that works in all browsers though).

https://github.com/zearp/Nucintosh/blob/master/EFI/OC/config.plist#L629-L630

**Comment by naryfa** [comment]
Hey, yes it highlighted. Thank you so much again. It works. Look at how fast the boot is now without TRIM. I don't know, perhaps it's mostly pertinent to Intel SATA SSDs. I attach the video sequence from the OC picker to the login screen (Sorry for quality, not sure how long will it remain online) . Shaved off about 40 seconds:

https://www.veed.io/view/0b966c7a-0b18-486e-b0da-b1bdb501bec8?sharingWidget=true

**Comment by zearp** [comment]
That's a good normal boot speed! How it should be. What model Intel disk to you have? I think the 600p series has some performance issues with macOs but others should be fine. My Samsung had some performance issues but it was fixed by updating to chelatest firmware.

I timed my boot but I use disk encryption so enter my password right after the picker and it takes about 20-25 seconds till the desktop shows and startup apps are done loading. I'm glad disabling has helped, I do wonder how/why it has so much trimming to do on boot that it takes 30+ seconds. I don't have any Intel disks test with.

You might be able to shave a few more seconds by disabling verbose boot. Instead of printing text it will show an Apple logo. I haven't measured it but it feels bit faster and it a lot cleaner. Verbose on by default just in case there's trouble installing.

**Comment by naryfa** [comment]
Very likely that Samsung drives have a better controller at this point. Like I mentioned, these Intel drives are 520 and 530 series. Both 480GB in size. Older models, so possibly quirky. But funny enough, I think you actually told me to disable TRIM in one of my ancient posts. So I still owe you a great deal of gratitude for the help.

I do like verbose, it always looked cool to me 😉 Perhaps I'll change it with time.
